document.addEventListener('DOMContentLoaded', function(){ var cy = cytoscape({ container: document.querySelector('#cy'), boxSelectionEnabled: false, zoomingEnabled: false, panningEnabled: true, autounselectify: true, style: cytoscape.stylesheet() .selector('node') .css({ 'content': 'data(id)', width: '60px', height: '60px', 'text-valign': 'center', 'color': '#333', 'text-outline-width': 2, 'text-outline-color': 'white', 'pie-size': '80%', 'pie-1-background-color': '#E8747C', 'pie-1-background-size': 'mapData(red, 0, 10, 0, 100)', 'pie-2-background-color': '#74E883', 'pie-2-background-size': 'mapData(green, 0, 10, 0, 100)' }) .selector('edge') .css({ 'target-arrow-shape': 'triangle' }) .selector(':selected') .css({ 'background-color': 'black', 'line-color': 'black', 'target-arrow-color': 'green', 'source-arrow-color': 'green' }) .selector('.faded') .css({ 'opacity': 0.15, 'text-opacity': 0 }),
elements: {nodes:[{ data: { id: 'MainGrid', red: 5, green: 5 } },
{ data: { id: 'Consumer 1', red: 10, green: 0 } },
{ data: { id: 'Consumer 2', red: 10, green: 0 } },
{ data: { id: 'Consumer 3', red: 10, green: 0 } },
{ data: { id: 'Consumer 4', red: 10, green: 0 } },
{ data: { id: 'Consumer 5', red: 10, green: 0 } },
{ data: { id: 'Consumer 6', red: 10, green: 0 } },
{ data: { id: 'Consumer 7', red: 10, green: 0 } },
{ data: { id: 'Consumer 8', red: 10, green: 0 } },
{ data: { id: 'Consumer 9', red: 10, green: 0 } },
{ data: { id: 'Consumer 10', red: 10, green: 0 } },
{ data: { id: 'Consumer 11', red: 10, green: 0 } },
{ data: { id: 'Consumer 12', red: 10, green: 0 } },
{ data: { id: 'Consumer 13', red: 10, green: 0 } },
{ data: { id: 'Consumer 14', red: 10, green: 0 } },
{ data: { id: 'Consumer 15', red: 10, green: 0 } },
{ data: { id: 'Consumer 16', red: 10, green: 0 } },
{ data: { id: 'Consumer 17', red: 10, green: 0 } },
{ data: { id: 'Consumer 18', red: 10, green: 0 } },
{ data: { id: 'Consumer 19', red: 10, green: 0 } },
{ data: { id: 'Consumer 20', red: 10, green: 0 } },
{ data: { id: 'Consumer 21', red: 10, green: 0 } },
{ data: { id: 'Consumer 22', red: 10, green: 0 } },
{ data: { id: 'Consumer 23', red: 10, green: 0 } },
{ data: { id: 'Consumer 24', red: 10, green: 0 } },
{ data: { id: 'Consumer 25', red: 10, green: 0 } },
{ data: { id: 'Solar 1', red: 0, green: 10 } },
{ data: { id: 'Solar 2', red: 0, green: 10 } },
{ data: { id: 'Solar 3', red: 0, green: 10 } },
{ data: { id: 'Solar 4', red: 0, green: 10 } },
{ data: { id: 'Solar 5', red: 0, green: 10 } },
{ data: { id: 'Solar 6', red: 0, green: 10 } },
{ data: { id: 'Solar 7', red: 0, green: 10 } },
{ data: { id: 'Solar 8', red: 0, green: 10 } },
{ data: { id: 'Solar 9', red: 0, green: 10 } },
{ data: { id: 'Solar 10', red: 0, green: 10 } },
{ data: { id: 'Wind 1', red: 0, green: 10 } },
{ data: { id: 'Wind 2', red: 0, green: 10 } },
{ data: { id: 'Wind 3', red: 0, green: 10 } },
{ data: { id: 'Wind 4', red: 0, green: 10 } },
{ data: { id: 'Wind 5', red: 0, green: 10 } },
{ data: { id: 'Wind 6', red: 0, green: 10 } },
{ data: { id: 'Wind 7', red: 0, green: 10 } },
{ data: { id: 'Wind 8', red: 0, green: 10 } },
{ data: { id: 'Wind 9', red: 0, green: 10 } },
{ data: { id: 'Wind 10', red: 0, green: 10 } },
{ data: { id: 'Storage 1', red: 5, green: 5 } },
{ data: { id: 'Storage 2', red: 5, green: 5 } },
{ data: { id: 'Storage 3', red: 5, green: 5 } },
{ data: { id: 'Storage 4', red: 5, green: 5 } },
{ data: { id: 'Storage 5', red: 5, green: 5 } },
{ data: { id: 'Storage 6', red: 5, green: 5 } },
{ data: { id: 'Storage 7', red: 5, green: 5 } },
{ data: { id: 'Storage 8', red: 5, green: 5 } },
],
edges:[{ data: { id: 'link00', weight: 1, source: 'Solar 6', target: 'MainGrid' } },
{ data: { id: 'link01', weight: 1, source: 'Solar 2', target: 'MainGrid' } },
{ data: { id: 'link02', weight: 1, source: 'Solar 10', target: 'MainGrid' } },
{ data: { id: 'link03', weight: 1, source: 'Solar 8', target: 'MainGrid' } },
{ data: { id: 'link04', weight: 1, source: 'Solar 5', target: 'MainGrid' } },
{ data: { id: 'link05', weight: 1, source: 'Solar 7', target: 'MainGrid' } },
{ data: { id: 'link06', weight: 1, source: 'Solar 9', target: 'MainGrid' } },
{ data: { id: 'link07', weight: 1, source: 'Solar 3', target: 'MainGrid' } },
{ data: { id: 'link08', weight: 1, source: 'Solar 1', target: 'MainGrid' } },
{ data: { id: 'link09', weight: 1, source: 'Solar 4', target: 'MainGrid' } },
{ data: { id: 'link010', weight: 1, source: 'Storage 7', target: 'MainGrid' } },
{ data: { id: 'link011', weight: 1, source: 'Storage 1', target: 'MainGrid' } },
{ data: { id: 'link012', weight: 1, source: 'Storage 2', target: 'MainGrid' } },
{ data: { id: 'link013', weight: 1, source: 'Storage 4', target: 'MainGrid' } },
{ data: { id: 'link014', weight: 1, source: 'Storage 6', target: 'MainGrid' } },
{ data: { id: 'link015', weight: 1, source: 'Storage 5', target: 'MainGrid' } },
{ data: { id: 'link016', weight: 1, source: 'Storage 3', target: 'MainGrid' } },
{ data: { id: 'link017', weight: 1, source: 'Storage 8', target: 'MainGrid' } },
{ data: { id: 'link018', weight: 1, source: 'Wind 5', target: 'MainGrid' } },
{ data: { id: 'link019', weight: 1, source: 'Wind 6', target: 'MainGrid' } },
{ data: { id: 'link020', weight: 1, source: 'Wind 8', target: 'MainGrid' } },
{ data: { id: 'link021', weight: 1, source: 'Wind 7', target: 'MainGrid' } },
{ data: { id: 'link022', weight: 1, source: 'Wind 1', target: 'MainGrid' } },
{ data: { id: 'link023', weight: 1, source: 'Wind 9', target: 'MainGrid' } },
{ data: { id: 'link024', weight: 1, source: 'Wind 3', target: 'MainGrid' } },
{ data: { id: 'link025', weight: 1, source: 'Wind 2', target: 'MainGrid' } },
{ data: { id: 'link026', weight: 1, source: 'Wind 4', target: 'MainGrid' } },
{ data: { id: 'link027', weight: 1, source: 'Wind 10', target: 'MainGrid' } },
{ data: { id: 'link10', weight: 1, source: 'Solar 2', target: 'Consumer 1' } },
{ data: { id: 'link11', weight: 1, source: 'Solar 10', target: 'Consumer 1' } },
{ data: { id: 'link12', weight: 1, source: 'Solar 8', target: 'Consumer 1' } },
{ data: { id: 'link13', weight: 1, source: 'Solar 5', target: 'Consumer 1' } },
{ data: { id: 'link14', weight: 1, source: 'Solar 9', target: 'Consumer 1' } },
{ data: { id: 'link15', weight: 1, source: 'Storage 7', target: 'Consumer 1' } },
{ data: { id: 'link16', weight: 1, source: 'Storage 1', target: 'Consumer 1' } },
{ data: { id: 'link17', weight: 1, source: 'Storage 4', target: 'Consumer 1' } },
{ data: { id: 'link18', weight: 1, source: 'Storage 6', target: 'Consumer 1' } },
{ data: { id: 'link19', weight: 1, source: 'Storage 5', target: 'Consumer 1' } },
{ data: { id: 'link110', weight: 1, source: 'MainGrid', target: 'Consumer 1' } },
{ data: { id: 'link111', weight: 1, source: 'Wind 8', target: 'Consumer 1' } },
{ data: { id: 'link112', weight: 1, source: 'Wind 1', target: 'Consumer 1' } },
{ data: { id: 'link113', weight: 1, source: 'Wind 3', target: 'Consumer 1' } },
{ data: { id: 'link114', weight: 1, source: 'Wind 2', target: 'Consumer 1' } },
{ data: { id: 'link115', weight: 1, source: 'Wind 4', target: 'Consumer 1' } },
{ data: { id: 'link20', weight: 1, source: 'Solar 2', target: 'Consumer 2' } },
{ data: { id: 'link21', weight: 1, source: 'Solar 8', target: 'Consumer 2' } },
{ data: { id: 'link22', weight: 1, source: 'Solar 5', target: 'Consumer 2' } },
{ data: { id: 'link23', weight: 1, source: 'Storage 7', target: 'Consumer 2' } },
{ data: { id: 'link24', weight: 1, source: 'Storage 1', target: 'Consumer 2' } },
{ data: { id: 'link25', weight: 1, source: 'Storage 2', target: 'Consumer 2' } },
{ data: { id: 'link26', weight: 1, source: 'Storage 4', target: 'Consumer 2' } },
{ data: { id: 'link27', weight: 1, source: 'Storage 8', target: 'Consumer 2' } },
{ data: { id: 'link28', weight: 1, source: 'MainGrid', target: 'Consumer 2' } },
{ data: { id: 'link29', weight: 1, source: 'Wind 5', target: 'Consumer 2' } },
{ data: { id: 'link210', weight: 1, source: 'Wind 6', target: 'Consumer 2' } },
{ data: { id: 'link211', weight: 1, source: 'Wind 8', target: 'Consumer 2' } },
{ data: { id: 'link212', weight: 1, source: 'Wind 7', target: 'Consumer 2' } },
{ data: { id: 'link213', weight: 1, source: 'Wind 1', target: 'Consumer 2' } },
{ data: { id: 'link214', weight: 1, source: 'Wind 9', target: 'Consumer 2' } },
{ data: { id: 'link215', weight: 1, source: 'Wind 10', target: 'Consumer 2' } },
{ data: { id: 'link30', weight: 1, source: 'Solar 6', target: 'Consumer 3' } },
{ data: { id: 'link31', weight: 1, source: 'Solar 2', target: 'Consumer 3' } },
{ data: { id: 'link32', weight: 1, source: 'Solar 8', target: 'Consumer 3' } },
{ data: { id: 'link33', weight: 1, source: 'Solar 5', target: 'Consumer 3' } },
{ data: { id: 'link34', weight: 1, source: 'Solar 3', target: 'Consumer 3' } },
{ data: { id: 'link35', weight: 1, source: 'Solar 1', target: 'Consumer 3' } },
{ data: { id: 'link36', weight: 1, source: 'Solar 4', target: 'Consumer 3' } },
{ data: { id: 'link37', weight: 1, source: 'Storage 7', target: 'Consumer 3' } },
{ data: { id: 'link38', weight: 1, source: 'Storage 1', target: 'Consumer 3' } },
{ data: { id: 'link39', weight: 1, source: 'Storage 4', target: 'Consumer 3' } },
{ data: { id: 'link310', weight: 1, source: 'Storage 5', target: 'Consumer 3' } },
{ data: { id: 'link311', weight: 1, source: 'Storage 3', target: 'Consumer 3' } },
{ data: { id: 'link312', weight: 1, source: 'MainGrid', target: 'Consumer 3' } },
{ data: { id: 'link313', weight: 1, source: 'Wind 5', target: 'Consumer 3' } },
{ data: { id: 'link314', weight: 1, source: 'Wind 8', target: 'Consumer 3' } },
{ data: { id: 'link315', weight: 1, source: 'Wind 2', target: 'Consumer 3' } },
{ data: { id: 'link40', weight: 1, source: 'Solar 2', target: 'Consumer 4' } },
{ data: { id: 'link41', weight: 1, source: 'Solar 10', target: 'Consumer 4' } },
{ data: { id: 'link42', weight: 1, source: 'Solar 8', target: 'Consumer 4' } },
{ data: { id: 'link43', weight: 1, source: 'Solar 5', target: 'Consumer 4' } },
{ data: { id: 'link44', weight: 1, source: 'Solar 7', target: 'Consumer 4' } },
{ data: { id: 'link45', weight: 1, source: 'Solar 9', target: 'Consumer 4' } },
{ data: { id: 'link46', weight: 1, source: 'Storage 7', target: 'Consumer 4' } },
{ data: { id: 'link47', weight: 1, source: 'Storage 1', target: 'Consumer 4' } },
{ data: { id: 'link48', weight: 1, source: 'Storage 4', target: 'Consumer 4' } },
{ data: { id: 'link49', weight: 1, source: 'Storage 6', target: 'Consumer 4' } },
{ data: { id: 'link410', weight: 1, source: 'Storage 8', target: 'Consumer 4' } },
{ data: { id: 'link411', weight: 1, source: 'MainGrid', target: 'Consumer 4' } },
{ data: { id: 'link412', weight: 1, source: 'Wind 5', target: 'Consumer 4' } },
{ data: { id: 'link413', weight: 1, source: 'Wind 8', target: 'Consumer 4' } },
{ data: { id: 'link414', weight: 1, source: 'Wind 1', target: 'Consumer 4' } },
{ data: { id: 'link415', weight: 1, source: 'Wind 2', target: 'Consumer 4' } },
{ data: { id: 'link50', weight: 1, source: 'Solar 6', target: 'Consumer 5' } },
{ data: { id: 'link51', weight: 1, source: 'Solar 2', target: 'Consumer 5' } },
{ data: { id: 'link52', weight: 1, source: 'Solar 9', target: 'Consumer 5' } },
{ data: { id: 'link53', weight: 1, source: 'Storage 7', target: 'Consumer 5' } },
{ data: { id: 'link54', weight: 1, source: 'Storage 1', target: 'Consumer 5' } },
{ data: { id: 'link55', weight: 1, source: 'Storage 2', target: 'Consumer 5' } },
{ data: { id: 'link56', weight: 1, source: 'Storage 4', target: 'Consumer 5' } },
{ data: { id: 'link57', weight: 1, source: 'Storage 3', target: 'Consumer 5' } },
{ data: { id: 'link58', weight: 1, source: 'MainGrid', target: 'Consumer 5' } },
{ data: { id: 'link59', weight: 1, source: 'Wind 5', target: 'Consumer 5' } },
{ data: { id: 'link510', weight: 1, source: 'Wind 6', target: 'Consumer 5' } },
{ data: { id: 'link511', weight: 1, source: 'Wind 8', target: 'Consumer 5' } },
{ data: { id: 'link512', weight: 1, source: 'Wind 7', target: 'Consumer 5' } },
{ data: { id: 'link513', weight: 1, source: 'Wind 3', target: 'Consumer 5' } },
{ data: { id: 'link514', weight: 1, source: 'Wind 2', target: 'Consumer 5' } },
{ data: { id: 'link515', weight: 1, source: 'Wind 4', target: 'Consumer 5' } },
{ data: { id: 'link60', weight: 1, source: 'Solar 6', target: 'Consumer 6' } },
{ data: { id: 'link61', weight: 1, source: 'Solar 2', target: 'Consumer 6' } },
{ data: { id: 'link62', weight: 1, source: 'Solar 9', target: 'Consumer 6' } },
{ data: { id: 'link63', weight: 1, source: 'Solar 3', target: 'Consumer 6' } },
{ data: { id: 'link64', weight: 1, source: 'Solar 1', target: 'Consumer 6' } },
{ data: { id: 'link65', weight: 1, source: 'Solar 4', target: 'Consumer 6' } },
{ data: { id: 'link66', weight: 1, source: 'Storage 7', target: 'Consumer 6' } },
{ data: { id: 'link67', weight: 1, source: 'Storage 1', target: 'Consumer 6' } },
{ data: { id: 'link68', weight: 1, source: 'Storage 4', target: 'Consumer 6' } },
{ data: { id: 'link69', weight: 1, source: 'Storage 6', target: 'Consumer 6' } },
{ data: { id: 'link610', weight: 1, source: 'Storage 5', target: 'Consumer 6' } },
{ data: { id: 'link611', weight: 1, source: 'MainGrid', target: 'Consumer 6' } },
{ data: { id: 'link612', weight: 1, source: 'Wind 5', target: 'Consumer 6' } },
{ data: { id: 'link613', weight: 1, source: 'Wind 8', target: 'Consumer 6' } },
{ data: { id: 'link614', weight: 1, source: 'Wind 9', target: 'Consumer 6' } },
{ data: { id: 'link615', weight: 1, source: 'Wind 2', target: 'Consumer 6' } },
{ data: { id: 'link616', weight: 1, source: 'Wind 10', target: 'Consumer 6' } },
{ data: { id: 'link70', weight: 1, source: 'Solar 6', target: 'Consumer 7' } },
{ data: { id: 'link71', weight: 1, source: 'Solar 10', target: 'Consumer 7' } },
{ data: { id: 'link72', weight: 1, source: 'Solar 8', target: 'Consumer 7' } },
{ data: { id: 'link73', weight: 1, source: 'Solar 5', target: 'Consumer 7' } },
{ data: { id: 'link74', weight: 1, source: 'Solar 7', target: 'Consumer 7' } },
{ data: { id: 'link75', weight: 1, source: 'Solar 9', target: 'Consumer 7' } },
{ data: { id: 'link76', weight: 1, source: 'Solar 3', target: 'Consumer 7' } },
{ data: { id: 'link77', weight: 1, source: 'Storage 7', target: 'Consumer 7' } },
{ data: { id: 'link78', weight: 1, source: 'Storage 1', target: 'Consumer 7' } },
{ data: { id: 'link79', weight: 1, source: 'Storage 4', target: 'Consumer 7' } },
{ data: { id: 'link710', weight: 1, source: 'Storage 8', target: 'Consumer 7' } },
{ data: { id: 'link711', weight: 1, source: 'MainGrid', target: 'Consumer 7' } },
{ data: { id: 'link712', weight: 1, source: 'Wind 5', target: 'Consumer 7' } },
{ data: { id: 'link713', weight: 1, source: 'Wind 8', target: 'Consumer 7' } },
{ data: { id: 'link714', weight: 1, source: 'Wind 2', target: 'Consumer 7' } },
{ data: { id: 'link80', weight: 1, source: 'Solar 6', target: 'Consumer 8' } },
{ data: { id: 'link81', weight: 1, source: 'Solar 9', target: 'Consumer 8' } },
{ data: { id: 'link82', weight: 1, source: 'Solar 3', target: 'Consumer 8' } },
{ data: { id: 'link83', weight: 1, source: 'Storage 1', target: 'Consumer 8' } },
{ data: { id: 'link84', weight: 1, source: 'Storage 2', target: 'Consumer 8' } },
{ data: { id: 'link85', weight: 1, source: 'Storage 4', target: 'Consumer 8' } },
{ data: { id: 'link86', weight: 1, source: 'Storage 5', target: 'Consumer 8' } },
{ data: { id: 'link87', weight: 1, source: 'Storage 3', target: 'Consumer 8' } },
{ data: { id: 'link88', weight: 1, source: 'Storage 8', target: 'Consumer 8' } },
{ data: { id: 'link89', weight: 1, source: 'MainGrid', target: 'Consumer 8' } },
{ data: { id: 'link810', weight: 1, source: 'Wind 5', target: 'Consumer 8' } },
{ data: { id: 'link811', weight: 1, source: 'Wind 6', target: 'Consumer 8' } },
{ data: { id: 'link812', weight: 1, source: 'Wind 8', target: 'Consumer 8' } },
{ data: { id: 'link813', weight: 1, source: 'Wind 1', target: 'Consumer 8' } },
{ data: { id: 'link814', weight: 1, source: 'Wind 3', target: 'Consumer 8' } },
{ data: { id: 'link815', weight: 1, source: 'Wind 2', target: 'Consumer 8' } },
{ data: { id: 'link816', weight: 1, source: 'Wind 4', target: 'Consumer 8' } },
{ data: { id: 'link90', weight: 1, source: 'Solar 6', target: 'Consumer 9' } },
{ data: { id: 'link91', weight: 1, source: 'Solar 2', target: 'Consumer 9' } },
{ data: { id: 'link92', weight: 1, source: 'Solar 9', target: 'Consumer 9' } },
{ data: { id: 'link93', weight: 1, source: 'Solar 3', target: 'Consumer 9' } },
{ data: { id: 'link94', weight: 1, source: 'Solar 1', target: 'Consumer 9' } },
{ data: { id: 'link95', weight: 1, source: 'Storage 7', target: 'Consumer 9' } },
{ data: { id: 'link96', weight: 1, source: 'Storage 2', target: 'Consumer 9' } },
{ data: { id: 'link97', weight: 1, source: 'Storage 6', target: 'Consumer 9' } },
{ data: { id: 'link98', weight: 1, source: 'Storage 5', target: 'Consumer 9' } },
{ data: { id: 'link99', weight: 1, source: 'Storage 8', target: 'Consumer 9' } },
{ data: { id: 'link910', weight: 1, source: 'MainGrid', target: 'Consumer 9' } },
{ data: { id: 'link911', weight: 1, source: 'Wind 5', target: 'Consumer 9' } },
{ data: { id: 'link912', weight: 1, source: 'Wind 8', target: 'Consumer 9' } },
{ data: { id: 'link913', weight: 1, source: 'Wind 7', target: 'Consumer 9' } },
{ data: { id: 'link914', weight: 1, source: 'Wind 9', target: 'Consumer 9' } },
{ data: { id: 'link915', weight: 1, source: 'Wind 2', target: 'Consumer 9' } },
{ data: { id: 'link916', weight: 1, source: 'Wind 10', target: 'Consumer 9' } },
{ data: { id: 'link100', weight: 1, source: 'Solar 6', target: 'Consumer 10' } },
{ data: { id: 'link101', weight: 1, source: 'Solar 8', target: 'Consumer 10' } },
{ data: { id: 'link102', weight: 1, source: 'Solar 5', target: 'Consumer 10' } },
{ data: { id: 'link103', weight: 1, source: 'Solar 7', target: 'Consumer 10' } },
{ data: { id: 'link104', weight: 1, source: 'Solar 9', target: 'Consumer 10' } },
{ data: { id: 'link105', weight: 1, source: 'Solar 3', target: 'Consumer 10' } },
{ data: { id: 'link106', weight: 1, source: 'Solar 4', target: 'Consumer 10' } },
{ data: { id: 'link107', weight: 1, source: 'Storage 1', target: 'Consumer 10' } },
{ data: { id: 'link108', weight: 1, source: 'Storage 2', target: 'Consumer 10' } },
{ data: { id: 'link109', weight: 1, source: 'Storage 5', target: 'Consumer 10' } },
{ data: { id: 'link1010', weight: 1, source: 'Storage 8', target: 'Consumer 10' } },
{ data: { id: 'link1011', weight: 1, source: 'MainGrid', target: 'Consumer 10' } },
{ data: { id: 'link1012', weight: 1, source: 'Wind 6', target: 'Consumer 10' } },
{ data: { id: 'link1013', weight: 1, source: 'Wind 9', target: 'Consumer 10' } },
{ data: { id: 'link1014', weight: 1, source: 'Wind 2', target: 'Consumer 10' } },
{ data: { id: 'link110', weight: 1, source: 'Solar 6', target: 'Consumer 11' } },
{ data: { id: 'link111', weight: 1, source: 'Solar 10', target: 'Consumer 11' } },
{ data: { id: 'link112', weight: 1, source: 'Solar 9', target: 'Consumer 11' } },
{ data: { id: 'link113', weight: 1, source: 'Solar 3', target: 'Consumer 11' } },
{ data: { id: 'link114', weight: 1, source: 'Storage 2', target: 'Consumer 11' } },
{ data: { id: 'link115', weight: 1, source: 'Storage 4', target: 'Consumer 11' } },
{ data: { id: 'link116', weight: 1, source: 'Storage 5', target: 'Consumer 11' } },
{ data: { id: 'link117', weight: 1, source: 'Storage 3', target: 'Consumer 11' } },
{ data: { id: 'link118', weight: 1, source: 'Storage 8', target: 'Consumer 11' } },
{ data: { id: 'link119', weight: 1, source: 'MainGrid', target: 'Consumer 11' } },
{ data: { id: 'link1110', weight: 1, source: 'Wind 6', target: 'Consumer 11' } },
{ data: { id: 'link1111', weight: 1, source: 'Wind 1', target: 'Consumer 11' } },
{ data: { id: 'link1112', weight: 1, source: 'Wind 9', target: 'Consumer 11' } },
{ data: { id: 'link1113', weight: 1, source: 'Wind 3', target: 'Consumer 11' } },
{ data: { id: 'link1114', weight: 1, source: 'Wind 2', target: 'Consumer 11' } },
{ data: { id: 'link1115', weight: 1, source: 'Wind 4', target: 'Consumer 11' } },
{ data: { id: 'link120', weight: 1, source: 'Solar 6', target: 'Consumer 12' } },
{ data: { id: 'link121', weight: 1, source: 'Solar 10', target: 'Consumer 12' } },
{ data: { id: 'link122', weight: 1, source: 'Solar 3', target: 'Consumer 12' } },
{ data: { id: 'link123', weight: 1, source: 'Storage 7', target: 'Consumer 12' } },
{ data: { id: 'link124', weight: 1, source: 'Storage 2', target: 'Consumer 12' } },
{ data: { id: 'link125', weight: 1, source: 'Storage 6', target: 'Consumer 12' } },
{ data: { id: 'link126', weight: 1, source: 'Storage 5', target: 'Consumer 12' } },
{ data: { id: 'link127', weight: 1, source: 'Storage 8', target: 'Consumer 12' } },
{ data: { id: 'link128', weight: 1, source: 'MainGrid', target: 'Consumer 12' } },
{ data: { id: 'link129', weight: 1, source: 'Wind 5', target: 'Consumer 12' } },
{ data: { id: 'link1210', weight: 1, source: 'Wind 6', target: 'Consumer 12' } },
{ data: { id: 'link1211', weight: 1, source: 'Wind 8', target: 'Consumer 12' } },
{ data: { id: 'link1212', weight: 1, source: 'Wind 7', target: 'Consumer 12' } },
{ data: { id: 'link1213', weight: 1, source: 'Wind 9', target: 'Consumer 12' } },
{ data: { id: 'link1214', weight: 1, source: 'Wind 3', target: 'Consumer 12' } },
{ data: { id: 'link1215', weight: 1, source: 'Wind 10', target: 'Consumer 12' } },
{ data: { id: 'link130', weight: 1, source: 'Solar 6', target: 'Consumer 13' } },
{ data: { id: 'link131', weight: 1, source: 'Solar 2', target: 'Consumer 13' } },
{ data: { id: 'link132', weight: 1, source: 'Solar 10', target: 'Consumer 13' } },
{ data: { id: 'link133', weight: 1, source: 'Solar 5', target: 'Consumer 13' } },
{ data: { id: 'link134', weight: 1, source: 'Solar 7', target: 'Consumer 13' } },
{ data: { id: 'link135', weight: 1, source: 'Solar 3', target: 'Consumer 13' } },
{ data: { id: 'link136', weight: 1, source: 'Solar 1', target: 'Consumer 13' } },
{ data: { id: 'link137', weight: 1, source: 'Solar 4', target: 'Consumer 13' } },
{ data: { id: 'link138', weight: 1, source: 'Storage 1', target: 'Consumer 13' } },
{ data: { id: 'link139', weight: 1, source: 'Storage 2', target: 'Consumer 13' } },
{ data: { id: 'link1310', weight: 1, source: 'Storage 5', target: 'Consumer 13' } },
{ data: { id: 'link1311', weight: 1, source: 'Storage 3', target: 'Consumer 13' } },
{ data: { id: 'link1312', weight: 1, source: 'Storage 8', target: 'Consumer 13' } },
{ data: { id: 'link1313', weight: 1, source: 'MainGrid', target: 'Consumer 13' } },
{ data: { id: 'link1314', weight: 1, source: 'Wind 6', target: 'Consumer 13' } },
{ data: { id: 'link1315', weight: 1, source: 'Wind 9', target: 'Consumer 13' } },
{ data: { id: 'link1316', weight: 1, source: 'Wind 3', target: 'Consumer 13' } },
{ data: { id: 'link140', weight: 1, source: 'Solar 10', target: 'Consumer 14' } },
{ data: { id: 'link141', weight: 1, source: 'Solar 8', target: 'Consumer 14' } },
{ data: { id: 'link142', weight: 1, source: 'Solar 7', target: 'Consumer 14' } },
{ data: { id: 'link143', weight: 1, source: 'Solar 9', target: 'Consumer 14' } },
{ data: { id: 'link144', weight: 1, source: 'Solar 4', target: 'Consumer 14' } },
{ data: { id: 'link145', weight: 1, source: 'Storage 2', target: 'Consumer 14' } },
{ data: { id: 'link146', weight: 1, source: 'Storage 4', target: 'Consumer 14' } },
{ data: { id: 'link147', weight: 1, source: 'Storage 6', target: 'Consumer 14' } },
{ data: { id: 'link148', weight: 1, source: 'Storage 5', target: 'Consumer 14' } },
{ data: { id: 'link149', weight: 1, source: 'Storage 8', target: 'Consumer 14' } },
{ data: { id: 'link1410', weight: 1, source: 'MainGrid', target: 'Consumer 14' } },
{ data: { id: 'link1411', weight: 1, source: 'Wind 6', target: 'Consumer 14' } },
{ data: { id: 'link1412', weight: 1, source: 'Wind 1', target: 'Consumer 14' } },
{ data: { id: 'link1413', weight: 1, source: 'Wind 9', target: 'Consumer 14' } },
{ data: { id: 'link1414', weight: 1, source: 'Wind 3', target: 'Consumer 14' } },
{ data: { id: 'link1415', weight: 1, source: 'Wind 2', target: 'Consumer 14' } },
{ data: { id: 'link150', weight: 1, source: 'Solar 10', target: 'Consumer 15' } },
{ data: { id: 'link151', weight: 1, source: 'Solar 7', target: 'Consumer 15' } },
{ data: { id: 'link152', weight: 1, source: 'Solar 1', target: 'Consumer 15' } },
{ data: { id: 'link153', weight: 1, source: 'Solar 4', target: 'Consumer 15' } },
{ data: { id: 'link154', weight: 1, source: 'Storage 7', target: 'Consumer 15' } },
{ data: { id: 'link155', weight: 1, source: 'Storage 1', target: 'Consumer 15' } },
{ data: { id: 'link156', weight: 1, source: 'Storage 2', target: 'Consumer 15' } },
{ data: { id: 'link157', weight: 1, source: 'Storage 5', target: 'Consumer 15' } },
{ data: { id: 'link158', weight: 1, source: 'Storage 8', target: 'Consumer 15' } },
{ data: { id: 'link159', weight: 1, source: 'MainGrid', target: 'Consumer 15' } },
{ data: { id: 'link1510', weight: 1, source: 'Wind 5', target: 'Consumer 15' } },
{ data: { id: 'link1511', weight: 1, source: 'Wind 6', target: 'Consumer 15' } },
{ data: { id: 'link1512', weight: 1, source: 'Wind 8', target: 'Consumer 15' } },
{ data: { id: 'link1513', weight: 1, source: 'Wind 7', target: 'Consumer 15' } },
{ data: { id: 'link1514', weight: 1, source: 'Wind 9', target: 'Consumer 15' } },
{ data: { id: 'link1515', weight: 1, source: 'Wind 3', target: 'Consumer 15' } },
{ data: { id: 'link1516', weight: 1, source: 'Wind 4', target: 'Consumer 15' } },
{ data: { id: 'link160', weight: 1, source: 'Solar 2', target: 'Consumer 16' } },
{ data: { id: 'link161', weight: 1, source: 'Solar 10', target: 'Consumer 16' } },
{ data: { id: 'link162', weight: 1, source: 'Solar 7', target: 'Consumer 16' } },
{ data: { id: 'link163', weight: 1, source: 'Solar 3', target: 'Consumer 16' } },
{ data: { id: 'link164', weight: 1, source: 'Solar 1', target: 'Consumer 16' } },
{ data: { id: 'link165', weight: 1, source: 'Solar 4', target: 'Consumer 16' } },
{ data: { id: 'link166', weight: 1, source: 'Storage 2', target: 'Consumer 16' } },
{ data: { id: 'link167', weight: 1, source: 'Storage 4', target: 'Consumer 16' } },
{ data: { id: 'link168', weight: 1, source: 'Storage 6', target: 'Consumer 16' } },
{ data: { id: 'link169', weight: 1, source: 'Storage 3', target: 'Consumer 16' } },
{ data: { id: 'link1610', weight: 1, source: 'MainGrid', target: 'Consumer 16' } },
{ data: { id: 'link1611', weight: 1, source: 'Wind 6', target: 'Consumer 16' } },
{ data: { id: 'link1612', weight: 1, source: 'Wind 9', target: 'Consumer 16' } },
{ data: { id: 'link1613', weight: 1, source: 'Wind 3', target: 'Consumer 16' } },
{ data: { id: 'link1614', weight: 1, source: 'Wind 10', target: 'Consumer 16' } },
{ data: { id: 'link170', weight: 1, source: 'Solar 6', target: 'Consumer 17' } },
{ data: { id: 'link171', weight: 1, source: 'Solar 10', target: 'Consumer 17' } },
{ data: { id: 'link172', weight: 1, source: 'Solar 8', target: 'Consumer 17' } },
{ data: { id: 'link173', weight: 1, source: 'Solar 5', target: 'Consumer 17' } },
{ data: { id: 'link174', weight: 1, source: 'Solar 7', target: 'Consumer 17' } },
{ data: { id: 'link175', weight: 1, source: 'Solar 9', target: 'Consumer 17' } },
{ data: { id: 'link176', weight: 1, source: 'Solar 1', target: 'Consumer 17' } },
{ data: { id: 'link177', weight: 1, source: 'Solar 4', target: 'Consumer 17' } },
{ data: { id: 'link178', weight: 1, source: 'Storage 7', target: 'Consumer 17' } },
{ data: { id: 'link179', weight: 1, source: 'Storage 6', target: 'Consumer 17' } },
{ data: { id: 'link1710', weight: 1, source: 'Storage 5', target: 'Consumer 17' } },
{ data: { id: 'link1711', weight: 1, source: 'Storage 3', target: 'Consumer 17' } },
{ data: { id: 'link1712', weight: 1, source: 'MainGrid', target: 'Consumer 17' } },
{ data: { id: 'link1713', weight: 1, source: 'Wind 6', target: 'Consumer 17' } },
{ data: { id: 'link1714', weight: 1, source: 'Wind 3', target: 'Consumer 17' } },
{ data: { id: 'link1715', weight: 1, source: 'Wind 10', target: 'Consumer 17' } },
{ data: { id: 'link180', weight: 1, source: 'Solar 10', target: 'Consumer 18' } },
{ data: { id: 'link181', weight: 1, source: 'Solar 7', target: 'Consumer 18' } },
{ data: { id: 'link182', weight: 1, source: 'Solar 1', target: 'Consumer 18' } },
{ data: { id: 'link183', weight: 1, source: 'Solar 4', target: 'Consumer 18' } },
{ data: { id: 'link184', weight: 1, source: 'Storage 1', target: 'Consumer 18' } },
{ data: { id: 'link185', weight: 1, source: 'Storage 2', target: 'Consumer 18' } },
{ data: { id: 'link186', weight: 1, source: 'Storage 6', target: 'Consumer 18' } },
{ data: { id: 'link187', weight: 1, source: 'Storage 3', target: 'Consumer 18' } },
{ data: { id: 'link188', weight: 1, source: 'Storage 8', target: 'Consumer 18' } },
{ data: { id: 'link189', weight: 1, source: 'MainGrid', target: 'Consumer 18' } },
{ data: { id: 'link1810', weight: 1, source: 'Wind 5', target: 'Consumer 18' } },
{ data: { id: 'link1811', weight: 1, source: 'Wind 6', target: 'Consumer 18' } },
{ data: { id: 'link1812', weight: 1, source: 'Wind 7', target: 'Consumer 18' } },
{ data: { id: 'link1813', weight: 1, source: 'Wind 1', target: 'Consumer 18' } },
{ data: { id: 'link1814', weight: 1, source: 'Wind 3', target: 'Consumer 18' } },
{ data: { id: 'link1815', weight: 1, source: 'Wind 2', target: 'Consumer 18' } },
{ data: { id: 'link1816', weight: 1, source: 'Wind 4', target: 'Consumer 18' } },
{ data: { id: 'link1817', weight: 1, source: 'Wind 10', target: 'Consumer 18' } },
{ data: { id: 'link190', weight: 1, source: 'Solar 2', target: 'Consumer 19' } },
{ data: { id: 'link191', weight: 1, source: 'Solar 10', target: 'Consumer 19' } },
{ data: { id: 'link192', weight: 1, source: 'Solar 7', target: 'Consumer 19' } },
{ data: { id: 'link193', weight: 1, source: 'Solar 1', target: 'Consumer 19' } },
{ data: { id: 'link194', weight: 1, source: 'Solar 4', target: 'Consumer 19' } },
{ data: { id: 'link195', weight: 1, source: 'Storage 4', target: 'Consumer 19' } },
{ data: { id: 'link196', weight: 1, source: 'Storage 6', target: 'Consumer 19' } },
{ data: { id: 'link197', weight: 1, source: 'Storage 5', target: 'Consumer 19' } },
{ data: { id: 'link198', weight: 1, source: 'Storage 3', target: 'Consumer 19' } },
{ data: { id: 'link199', weight: 1, source: 'MainGrid', target: 'Consumer 19' } },
{ data: { id: 'link1910', weight: 1, source: 'Wind 8', target: 'Consumer 19' } },
{ data: { id: 'link1911', weight: 1, source: 'Wind 7', target: 'Consumer 19' } },
{ data: { id: 'link1912', weight: 1, source: 'Wind 9', target: 'Consumer 19' } },
{ data: { id: 'link1913', weight: 1, source: 'Wind 4', target: 'Consumer 19' } },
{ data: { id: 'link1914', weight: 1, source: 'Wind 10', target: 'Consumer 19' } },
{ data: { id: 'link200', weight: 1, source: 'Solar 6', target: 'Consumer 20' } },
{ data: { id: 'link201', weight: 1, source: 'Solar 8', target: 'Consumer 20' } },
{ data: { id: 'link202', weight: 1, source: 'Solar 5', target: 'Consumer 20' } },
{ data: { id: 'link203', weight: 1, source: 'Solar 7', target: 'Consumer 20' } },
{ data: { id: 'link204', weight: 1, source: 'Solar 3', target: 'Consumer 20' } },
{ data: { id: 'link205', weight: 1, source: 'Solar 1', target: 'Consumer 20' } },
{ data: { id: 'link206', weight: 1, source: 'Solar 4', target: 'Consumer 20' } },
{ data: { id: 'link207', weight: 1, source: 'Storage 7', target: 'Consumer 20' } },
{ data: { id: 'link208', weight: 1, source: 'Storage 6', target: 'Consumer 20' } },
{ data: { id: 'link209', weight: 1, source: 'Storage 3', target: 'Consumer 20' } },
{ data: { id: 'link2010', weight: 1, source: 'Storage 8', target: 'Consumer 20' } },
{ data: { id: 'link2011', weight: 1, source: 'MainGrid', target: 'Consumer 20' } },
{ data: { id: 'link2012', weight: 1, source: 'Wind 7', target: 'Consumer 20' } },
{ data: { id: 'link2013', weight: 1, source: 'Wind 1', target: 'Consumer 20' } },
{ data: { id: 'link2014', weight: 1, source: 'Wind 4', target: 'Consumer 20' } },
{ data: { id: 'link2015', weight: 1, source: 'Wind 10', target: 'Consumer 20' } },
{ data: { id: 'link210', weight: 1, source: 'Solar 10', target: 'Consumer 21' } },
{ data: { id: 'link211', weight: 1, source: 'Solar 8', target: 'Consumer 21' } },
{ data: { id: 'link212', weight: 1, source: 'Solar 9', target: 'Consumer 21' } },
{ data: { id: 'link213', weight: 1, source: 'Solar 1', target: 'Consumer 21' } },
{ data: { id: 'link214', weight: 1, source: 'Solar 4', target: 'Consumer 21' } },
{ data: { id: 'link215', weight: 1, source: 'Storage 1', target: 'Consumer 21' } },
{ data: { id: 'link216', weight: 1, source: 'Storage 2', target: 'Consumer 21' } },
{ data: { id: 'link217', weight: 1, source: 'Storage 6', target: 'Consumer 21' } },
{ data: { id: 'link218', weight: 1, source: 'Storage 3', target: 'Consumer 21' } },
{ data: { id: 'link219', weight: 1, source: 'MainGrid', target: 'Consumer 21' } },
{ data: { id: 'link2110', weight: 1, source: 'Wind 7', target: 'Consumer 21' } },
{ data: { id: 'link2111', weight: 1, source: 'Wind 1', target: 'Consumer 21' } },
{ data: { id: 'link2112', weight: 1, source: 'Wind 3', target: 'Consumer 21' } },
{ data: { id: 'link2113', weight: 1, source: 'Wind 2', target: 'Consumer 21' } },
{ data: { id: 'link2114', weight: 1, source: 'Wind 4', target: 'Consumer 21' } },
{ data: { id: 'link2115', weight: 1, source: 'Wind 10', target: 'Consumer 21' } },
{ data: { id: 'link220', weight: 1, source: 'Solar 8', target: 'Consumer 22' } },
{ data: { id: 'link221', weight: 1, source: 'Solar 5', target: 'Consumer 22' } },
{ data: { id: 'link222', weight: 1, source: 'Solar 1', target: 'Consumer 22' } },
{ data: { id: 'link223', weight: 1, source: 'Storage 4', target: 'Consumer 22' } },
{ data: { id: 'link224', weight: 1, source: 'Storage 6', target: 'Consumer 22' } },
{ data: { id: 'link225', weight: 1, source: 'Storage 5', target: 'Consumer 22' } },
{ data: { id: 'link226', weight: 1, source: 'Storage 3', target: 'Consumer 22' } },
{ data: { id: 'link227', weight: 1, source: 'MainGrid', target: 'Consumer 22' } },
{ data: { id: 'link228', weight: 1, source: 'Wind 5', target: 'Consumer 22' } },
{ data: { id: 'link229', weight: 1, source: 'Wind 6', target: 'Consumer 22' } },
{ data: { id: 'link2210', weight: 1, source: 'Wind 8', target: 'Consumer 22' } },
{ data: { id: 'link2211', weight: 1, source: 'Wind 7', target: 'Consumer 22' } },
{ data: { id: 'link2212', weight: 1, source: 'Wind 1', target: 'Consumer 22' } },
{ data: { id: 'link2213', weight: 1, source: 'Wind 9', target: 'Consumer 22' } },
{ data: { id: 'link2214', weight: 1, source: 'Wind 4', target: 'Consumer 22' } },
{ data: { id: 'link2215', weight: 1, source: 'Wind 10', target: 'Consumer 22' } },
{ data: { id: 'link230', weight: 1, source: 'Solar 6', target: 'Consumer 23' } },
{ data: { id: 'link231', weight: 1, source: 'Solar 2', target: 'Consumer 23' } },
{ data: { id: 'link232', weight: 1, source: 'Solar 8', target: 'Consumer 23' } },
{ data: { id: 'link233', weight: 1, source: 'Solar 5', target: 'Consumer 23' } },
{ data: { id: 'link234', weight: 1, source: 'Solar 3', target: 'Consumer 23' } },
{ data: { id: 'link235', weight: 1, source: 'Solar 1', target: 'Consumer 23' } },
{ data: { id: 'link236', weight: 1, source: 'Solar 4', target: 'Consumer 23' } },
{ data: { id: 'link237', weight: 1, source: 'Storage 7', target: 'Consumer 23' } },
{ data: { id: 'link238', weight: 1, source: 'Storage 1', target: 'Consumer 23' } },
{ data: { id: 'link239', weight: 1, source: 'Storage 6', target: 'Consumer 23' } },
{ data: { id: 'link2310', weight: 1, source: 'Storage 3', target: 'Consumer 23' } },
{ data: { id: 'link2311', weight: 1, source: 'Storage 8', target: 'Consumer 23' } },
{ data: { id: 'link2312', weight: 1, source: 'MainGrid', target: 'Consumer 23' } },
{ data: { id: 'link2313', weight: 1, source: 'Wind 7', target: 'Consumer 23' } },
{ data: { id: 'link2314', weight: 1, source: 'Wind 1', target: 'Consumer 23' } },
{ data: { id: 'link2315', weight: 1, source: 'Wind 4', target: 'Consumer 23' } },
{ data: { id: 'link2316', weight: 1, source: 'Wind 10', target: 'Consumer 23' } },
{ data: { id: 'link240', weight: 1, source: 'Solar 2', target: 'Consumer 24' } },
{ data: { id: 'link241', weight: 1, source: 'Solar 10', target: 'Consumer 24' } },
{ data: { id: 'link242', weight: 1, source: 'Solar 8', target: 'Consumer 24' } },
{ data: { id: 'link243', weight: 1, source: 'Solar 5', target: 'Consumer 24' } },
{ data: { id: 'link244', weight: 1, source: 'Solar 7', target: 'Consumer 24' } },
{ data: { id: 'link245', weight: 1, source: 'Solar 9', target: 'Consumer 24' } },
{ data: { id: 'link246', weight: 1, source: 'Storage 7', target: 'Consumer 24' } },
{ data: { id: 'link247', weight: 1, source: 'Storage 2', target: 'Consumer 24' } },
{ data: { id: 'link248', weight: 1, source: 'Storage 4', target: 'Consumer 24' } },
{ data: { id: 'link249', weight: 1, source: 'Storage 3', target: 'Consumer 24' } },
{ data: { id: 'link2410', weight: 1, source: 'MainGrid', target: 'Consumer 24' } },
{ data: { id: 'link2411', weight: 1, source: 'Wind 7', target: 'Consumer 24' } },
{ data: { id: 'link2412', weight: 1, source: 'Wind 1', target: 'Consumer 24' } },
{ data: { id: 'link2413', weight: 1, source: 'Wind 2', target: 'Consumer 24' } },
{ data: { id: 'link2414', weight: 1, source: 'Wind 4', target: 'Consumer 24' } },
{ data: { id: 'link2415', weight: 1, source: 'Wind 10', target: 'Consumer 24' } },
{ data: { id: 'link250', weight: 1, source: 'Solar 2', target: 'Consumer 25' } },
{ data: { id: 'link251', weight: 1, source: 'Solar 8', target: 'Consumer 25' } },
{ data: { id: 'link252', weight: 1, source: 'Solar 5', target: 'Consumer 25' } },
{ data: { id: 'link253', weight: 1, source: 'Storage 7', target: 'Consumer 25' } },
{ data: { id: 'link254', weight: 1, source: 'Storage 4', target: 'Consumer 25' } },
{ data: { id: 'link255', weight: 1, source: 'Storage 6', target: 'Consumer 25' } },
{ data: { id: 'link256', weight: 1, source: 'Storage 5', target: 'Consumer 25' } },
{ data: { id: 'link257', weight: 1, source: 'MainGrid', target: 'Consumer 25' } },
{ data: { id: 'link258', weight: 1, source: 'Wind 5', target: 'Consumer 25' } },
{ data: { id: 'link259', weight: 1, source: 'Wind 6', target: 'Consumer 25' } },
{ data: { id: 'link2510', weight: 1, source: 'Wind 8', target: 'Consumer 25' } },
{ data: { id: 'link2511', weight: 1, source: 'Wind 7', target: 'Consumer 25' } },
{ data: { id: 'link2512', weight: 1, source: 'Wind 1', target: 'Consumer 25' } },
{ data: { id: 'link2513', weight: 1, source: 'Wind 3', target: 'Consumer 25' } },
{ data: { id: 'link2514', weight: 1, source: 'Wind 4', target: 'Consumer 25' } },
{ data: { id: 'link460', weight: 1, source: 'Solar 6', target: 'Storage 1' } },
{ data: { id: 'link461', weight: 1, source: 'Solar 2', target: 'Storage 1' } },
{ data: { id: 'link462', weight: 1, source: 'Solar 5', target: 'Storage 1' } },
{ data: { id: 'link463', weight: 1, source: 'Solar 9', target: 'Storage 1' } },
{ data: { id: 'link464', weight: 1, source: 'Solar 3', target: 'Storage 1' } },
{ data: { id: 'link465', weight: 1, source: 'Solar 1', target: 'Storage 1' } },
{ data: { id: 'link466', weight: 1, source: 'Solar 4', target: 'Storage 1' } },
{ data: { id: 'link467', weight: 1, source: 'MainGrid', target: 'Storage 1' } },
{ data: { id: 'link468', weight: 1, source: 'Wind 7', target: 'Storage 1' } },
{ data: { id: 'link469', weight: 1, source: 'Wind 1', target: 'Storage 1' } },
{ data: { id: 'link4610', weight: 1, source: 'Wind 9', target: 'Storage 1' } },
{ data: { id: 'link4611', weight: 1, source: 'Wind 4', target: 'Storage 1' } },
{ data: { id: 'link470', weight: 1, source: 'Solar 6', target: 'Storage 2' } },
{ data: { id: 'link471', weight: 1, source: 'Solar 10', target: 'Storage 2' } },
{ data: { id: 'link472', weight: 1, source: 'Solar 8', target: 'Storage 2' } },
{ data: { id: 'link473', weight: 1, source: 'Solar 7', target: 'Storage 2' } },
{ data: { id: 'link474', weight: 1, source: 'Solar 9', target: 'Storage 2' } },
{ data: { id: 'link475', weight: 1, source: 'Solar 1', target: 'Storage 2' } },
{ data: { id: 'link476', weight: 1, source: 'Solar 4', target: 'Storage 2' } },
{ data: { id: 'link477', weight: 1, source: 'MainGrid', target: 'Storage 2' } },
{ data: { id: 'link478', weight: 1, source: 'Wind 7', target: 'Storage 2' } },
{ data: { id: 'link479', weight: 1, source: 'Wind 1', target: 'Storage 2' } },
{ data: { id: 'link4710', weight: 1, source: 'Wind 2', target: 'Storage 2' } },
{ data: { id: 'link4711', weight: 1, source: 'Wind 4', target: 'Storage 2' } },
{ data: { id: 'link4712', weight: 1, source: 'Wind 10', target: 'Storage 2' } },
{ data: { id: 'link480', weight: 1, source: 'Solar 7', target: 'Storage 3' } },
{ data: { id: 'link481', weight: 1, source: 'Solar 9', target: 'Storage 3' } },
{ data: { id: 'link482', weight: 1, source: 'Solar 1', target: 'Storage 3' } },
{ data: { id: 'link483', weight: 1, source: 'Solar 4', target: 'Storage 3' } },
{ data: { id: 'link484', weight: 1, source: 'MainGrid', target: 'Storage 3' } },
{ data: { id: 'link485', weight: 1, source: 'Wind 5', target: 'Storage 3' } },
{ data: { id: 'link486', weight: 1, source: 'Wind 6', target: 'Storage 3' } },
{ data: { id: 'link487', weight: 1, source: 'Wind 8', target: 'Storage 3' } },
{ data: { id: 'link488', weight: 1, source: 'Wind 7', target: 'Storage 3' } },
{ data: { id: 'link489', weight: 1, source: 'Wind 3', target: 'Storage 3' } },
{ data: { id: 'link4810', weight: 1, source: 'Wind 2', target: 'Storage 3' } },
{ data: { id: 'link4811', weight: 1, source: 'Wind 4', target: 'Storage 3' } },
{ data: { id: 'link4812', weight: 1, source: 'Wind 10', target: 'Storage 3' } },
{ data: { id: 'link490', weight: 1, source: 'Solar 2', target: 'Storage 4' } },
{ data: { id: 'link491', weight: 1, source: 'Solar 10', target: 'Storage 4' } },
{ data: { id: 'link492', weight: 1, source: 'Solar 7', target: 'Storage 4' } },
{ data: { id: 'link493', weight: 1, source: 'Solar 3', target: 'Storage 4' } },
{ data: { id: 'link494', weight: 1, source: 'Solar 1', target: 'Storage 4' } },
{ data: { id: 'link495', weight: 1, source: 'Solar 4', target: 'Storage 4' } },
{ data: { id: 'link496', weight: 1, source: 'MainGrid', target: 'Storage 4' } },
{ data: { id: 'link497', weight: 1, source: 'Wind 5', target: 'Storage 4' } },
{ data: { id: 'link498', weight: 1, source: 'Wind 8', target: 'Storage 4' } },
{ data: { id: 'link499', weight: 1, source: 'Wind 9', target: 'Storage 4' } },
{ data: { id: 'link4910', weight: 1, source: 'Wind 2', target: 'Storage 4' } },
{ data: { id: 'link4911', weight: 1, source: 'Wind 10', target: 'Storage 4' } },
{ data: { id: 'link500', weight: 1, source: 'Solar 6', target: 'Storage 5' } },
{ data: { id: 'link501', weight: 1, source: 'Solar 2', target: 'Storage 5' } },
{ data: { id: 'link502', weight: 1, source: 'Solar 10', target: 'Storage 5' } },
{ data: { id: 'link503', weight: 1, source: 'Solar 8', target: 'Storage 5' } },
{ data: { id: 'link504', weight: 1, source: 'Solar 5', target: 'Storage 5' } },
{ data: { id: 'link505', weight: 1, source: 'Solar 7', target: 'Storage 5' } },
{ data: { id: 'link506', weight: 1, source: 'Solar 9', target: 'Storage 5' } },
{ data: { id: 'link507', weight: 1, source: 'MainGrid', target: 'Storage 5' } },
{ data: { id: 'link508', weight: 1, source: 'Wind 5', target: 'Storage 5' } },
{ data: { id: 'link509', weight: 1, source: 'Wind 8', target: 'Storage 5' } },
{ data: { id: 'link5010', weight: 1, source: 'Wind 3', target: 'Storage 5' } },
{ data: { id: 'link510', weight: 1, source: 'Solar 2', target: 'Storage 6' } },
{ data: { id: 'link511', weight: 1, source: 'Solar 10', target: 'Storage 6' } },
{ data: { id: 'link512', weight: 1, source: 'Solar 8', target: 'Storage 6' } },
{ data: { id: 'link513', weight: 1, source: 'Solar 5', target: 'Storage 6' } },
{ data: { id: 'link514', weight: 1, source: 'MainGrid', target: 'Storage 6' } },
{ data: { id: 'link515', weight: 1, source: 'Wind 5', target: 'Storage 6' } },
{ data: { id: 'link516', weight: 1, source: 'Wind 6', target: 'Storage 6' } },
{ data: { id: 'link517', weight: 1, source: 'Wind 8', target: 'Storage 6' } },
{ data: { id: 'link518', weight: 1, source: 'Wind 1', target: 'Storage 6' } },
{ data: { id: 'link519', weight: 1, source: 'Wind 3', target: 'Storage 6' } },
{ data: { id: 'link5110', weight: 1, source: 'Wind 2', target: 'Storage 6' } },
{ data: { id: 'link5111', weight: 1, source: 'Wind 4', target: 'Storage 6' } },
{ data: { id: 'link520', weight: 1, source: 'Solar 2', target: 'Storage 7' } },
{ data: { id: 'link521', weight: 1, source: 'Solar 8', target: 'Storage 7' } },
{ data: { id: 'link522', weight: 1, source: 'Solar 5', target: 'Storage 7' } },
{ data: { id: 'link523', weight: 1, source: 'Solar 3', target: 'Storage 7' } },
{ data: { id: 'link524', weight: 1, source: 'Solar 1', target: 'Storage 7' } },
{ data: { id: 'link525', weight: 1, source: 'MainGrid', target: 'Storage 7' } },
{ data: { id: 'link526', weight: 1, source: 'Wind 6', target: 'Storage 7' } },
{ data: { id: 'link527', weight: 1, source: 'Wind 8', target: 'Storage 7' } },
{ data: { id: 'link528', weight: 1, source: 'Wind 7', target: 'Storage 7' } },
{ data: { id: 'link529', weight: 1, source: 'Wind 1', target: 'Storage 7' } },
{ data: { id: 'link5210', weight: 1, source: 'Wind 9', target: 'Storage 7' } },
{ data: { id: 'link5211', weight: 1, source: 'Wind 3', target: 'Storage 7' } },
{ data: { id: 'link5212', weight: 1, source: 'Wind 10', target: 'Storage 7' } },
{ data: { id: 'link530', weight: 1, source: 'Solar 6', target: 'Storage 8' } },
{ data: { id: 'link531', weight: 1, source: 'Solar 8', target: 'Storage 8' } },
{ data: { id: 'link532', weight: 1, source: 'Solar 5', target: 'Storage 8' } },
{ data: { id: 'link533', weight: 1, source: 'Solar 7', target: 'Storage 8' } },
{ data: { id: 'link534', weight: 1, source: 'Solar 3', target: 'Storage 8' } },
{ data: { id: 'link535', weight: 1, source: 'Solar 4', target: 'Storage 8' } },
{ data: { id: 'link536', weight: 1, source: 'MainGrid', target: 'Storage 8' } },
{ data: { id: 'link537', weight: 1, source: 'Wind 6', target: 'Storage 8' } },
{ data: { id: 'link538', weight: 1, source: 'Wind 1', target: 'Storage 8' } },
{ data: { id: 'link539', weight: 1, source: 'Wind 9', target: 'Storage 8' } },
{ data: { id: 'link5310', weight: 1, source: 'Wind 4', target: 'Storage 8' } },
]},
layout: { /*ring, grid and*/ name: 'grid', padding: 10 } }); cy.on('tap', 'node', function(e){ var node = e.cyTarget; var neighborhood = node.neighborhood().add(node); cy.elements().addClass('faded'); neighborhood.removeClass('faded'); }); cy.on('tap', function(e){ if( e.cyTarget === cy ){ cy.elements().removeClass('faded'); } }); });
$( document ).ready(function() {$('#agentData tbody').append('<tr id="tidMainGrid"><td>MainGrid</td><td>$0.01</td><td>$1</td><td>$436.77</td><td>$85048.26</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 1"><td>Consumer 1</td><td>$0.49</td><td>$0.00</td><td>-$19.94</td><td>-$3669.86</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 2"><td>Consumer 2</td><td>$0.45</td><td>$0.00</td><td>-$19.74</td><td>-$3677.35</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 3"><td>Consumer 3</td><td>$0.48</td><td>$0.00</td><td>-$20.46</td><td>-$3642.7</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 4"><td>Consumer 4</td><td>$0.53</td><td>$0.00</td><td>-$20.11</td><td>-$3707.87</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 5"><td>Consumer 5</td><td>$0.48</td><td>$0.00</td><td>-$17.65</td><td>-$3273.83</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 6"><td>Consumer 6</td><td>$0.49</td><td>$0.00</td><td>-$19.83</td><td>-$3666.41</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 7"><td>Consumer 7</td><td>$0.48</td><td>$0.00</td><td>-$19.11</td><td>-$3476.02</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 8"><td>Consumer 8</td><td>$0.48</td><td>$0.00</td><td>-$18.76</td><td>-$3624.82</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 9"><td>Consumer 9</td><td>$0.51</td><td>$0.00</td><td>-$19.6</td><td>-$3652.31</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 10"><td>Consumer 10</td><td>$0.49</td><td>$0.00</td><td>-$18</td><td>-$3652.36</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 11"><td>Consumer 11</td><td>$0.52</td><td>$0.00</td><td>-$17.64</td><td>-$3689.34</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 12"><td>Consumer 12</td><td>$0.54</td><td>$0.00</td><td>-$16.12</td><td>-$3350.32</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 13"><td>Consumer 13</td><td>$0.52</td><td>$0.00</td><td>-$19.11</td><td>-$3457.23</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 14"><td>Consumer 14</td><td>$0.57</td><td>$0.00</td><td>-$19</td><td>-$3623.3</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 15"><td>Consumer 15</td><td>$0.51</td><td>$0.00</td><td>-$17.89</td><td>-$3690.4</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 16"><td>Consumer 16</td><td>$0.51</td><td>$0.00</td><td>-$18.77</td><td>-$3665.52</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 17"><td>Consumer 17</td><td>$0.51</td><td>$0.00</td><td>-$19.47</td><td>-$3691.06</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 18"><td>Consumer 18</td><td>$0.54</td><td>$0.00</td><td>-$18.68</td><td>-$3490.91</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 19"><td>Consumer 19</td><td>$0.47</td><td>$0.00</td><td>-$17.59</td><td>-$3628.03</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 20"><td>Consumer 20</td><td>$0.49</td><td>$0.00</td><td>-$18.39</td><td>-$3696.08</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 21"><td>Consumer 21</td><td>$0.5</td><td>$0.00</td><td>-$19.34</td><td>-$3668.17</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 22"><td>Consumer 22</td><td>$0.56</td><td>$0.00</td><td>-$17.52</td><td>-$3396.7</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 23"><td>Consumer 23</td><td>$0.55</td><td>$0.00</td><td>-$16</td><td>-$3675.31</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 24"><td>Consumer 24</td><td>$0.52</td><td>$0.00</td><td>-$19.31</td><td>-$3660.88</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 25"><td>Consumer 25</td><td>$0.53</td><td>$0.00</td><td>-$17.62</td><td>-$3652.69</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 1"><td>Solar 1</td><td>$0.00</td><td>$0.22</td><td>$2.61</td><td>$404.22</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 2"><td>Solar 2</td><td>$0.00</td><td>$0.19</td><td>$3.23</td><td>$419.66</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 3"><td>Solar 3</td><td>$0.00</td><td>$0.22</td><td>$1.04</td><td>$402.61</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 4"><td>Solar 4</td><td>$0.00</td><td>$0.22</td><td>$2.48</td><td>$396.1</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 5"><td>Solar 5</td><td>$0.00</td><td>$0.21</td><td>$1.49</td><td>$414.97</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 6"><td>Solar 6</td><td>$0.00</td><td>$0.19</td><td>$3.86</td><td>$402.71</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 7"><td>Solar 7</td><td>$0.00</td><td>$0.21</td><td>$2.34</td><td>$417.12</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 8"><td>Solar 8</td><td>$0.00</td><td>$0.2</td><td>$1.09</td><td>$415.93</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 9"><td>Solar 9</td><td>$0.00</td><td>$0.22</td><td>$1.63</td><td>$386.95</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 10"><td>Solar 10</td><td>$0.00</td><td>$0.2</td><td>$0.49</td><td>$403.37</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 1"><td>Wind 1</td><td>$0.00</td><td>$1.6</td><td>$1.89</td><td>$253.45</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 2"><td>Wind 2</td><td>$0.00</td><td>$1.6</td><td>$0.76</td><td>$251.73</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 3"><td>Wind 3</td><td>$0.00</td><td>$1.6</td><td>$0.16</td><td>$242.61</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 4"><td>Wind 4</td><td>$0.00</td><td>$1.6</td><td>$2.46</td><td>$257.81</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 5"><td>Wind 5</td><td>$0.00</td><td>$1.6</td><td>$1.31</td><td>$253.26</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 6"><td>Wind 6</td><td>$0.00</td><td>$1.6</td><td>$0.16</td><td>$237.38</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 7"><td>Wind 7</td><td>$0.00</td><td>$1.6</td><td>$1.3</td><td>$230.14</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 8"><td>Wind 8</td><td>$0.00</td><td>$1.6</td><td>$0.74</td><td>$253.34</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 9"><td>Wind 9</td><td>$0.00</td><td>$1.6</td><td>$1.31</td><td>$261.59</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 10"><td>Wind 10</td><td>$0.00</td><td>$1.6</td><td>$1.9</td><td>$255.34</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 1"><td>Storage 1</td><td>$0.59</td><td>$0.59</td><td>$-0.43</td><td>$-193.7</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 2"><td>Storage 2</td><td>$0.61</td><td>$0.61</td><td>$-0.15</td><td>$-186.96</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 3"><td>Storage 3</td><td>$0.64</td><td>$0.64</td><td>$-0.43</td><td>$-188.09</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 4"><td>Storage 4</td><td>$0.61</td><td>$0.61</td><td>$-0.37</td><td>$-190.71</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 5"><td>Storage 5</td><td>$0.63</td><td>$0.63</td><td>$-0.79</td><td>$-190.92</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 6"><td>Storage 6</td><td>$0.63</td><td>$0.63</td><td>$-0.18</td><td>$-189.28</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 7"><td>Storage 7</td><td>$0.59</td><td>$0.59</td><td>$-0.43</td><td>$-194.82</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 8"><td>Storage 8</td><td>$0.66</td><td>$0.66</td><td>$-0.57</td><td>$-194.62</td></tr>');
$('#cCount').text('25');$('#gCount').text('20');$('#sCount').text('9');$('#dCount').text('197');});
