document.addEventListener('DOMContentLoaded', function(){ var cy = cytoscape({ container: document.querySelector('#cy'), boxSelectionEnabled: false, autounselectify: true, style: cytoscape.stylesheet() .selector('node') .css({ 'content': 'data(id)', width: '60px', height: '60px', 'text-valign': 'center', 'color': 'white', 'text-outline-width': 2, 'text-outline-color': '#888', 'pie-size': '80%', 'pie-1-background-color': '#E8747C', 'pie-1-background-size': 'mapData(foo, 0, 10, 0, 100)', 'pie-2-background-color': '#74CBE8', 'pie-2-background-size': 'mapData(bar, 0, 10, 0, 100)', 'pie-3-background-color': '#74E883', 'pie-3-background-size': 'mapData(baz, 0, 10, 0, 100)' }) .selector('edge') .css({ 'target-arrow-shape': 'triangle' }) .selector(':selected') .css({ 'background-color': 'black', 'line-color': 'green', 'target-arrow-color': 'green', 'source-arrow-color': 'green' }) .selector('.faded') .css({ 'opacity': 0.15, 'text-opacity': 0 }),
elements: {nodes:[{ data: { id: 'MainGrid', foo: 3, bar: 3, baz: 4 } },
{ data: { id: 'Consumer 1', foo: 3, bar: 3, baz: 4 } },
{ data: { id: 'Consumer 2', foo: 3, bar: 3, baz: 4 } },
{ data: { id: 'Consumer 3', foo: 3, bar: 3, baz: 4 } },
{ data: { id: 'Consumer 4', foo: 3, bar: 3, baz: 4 } },
{ data: { id: 'Consumer 5', foo: 3, bar: 3, baz: 4 } },
{ data: { id: 'Solar 1', foo: 3, bar: 3, baz: 4 } },
{ data: { id: 'Solar 2', foo: 3, bar: 3, baz: 4 } },
{ data: { id: 'Solar 3', foo: 3, bar: 3, baz: 4 } },
{ data: { id: 'Wind 1', foo: 3, bar: 3, baz: 4 } },
{ data: { id: 'Wind 2', foo: 3, bar: 3, baz: 4 } },
{ data: { id: 'Wind 3', foo: 3, bar: 3, baz: 4 } },
{ data: { id: 'Wind 4', foo: 3, bar: 3, baz: 4 } },
{ data: { id: 'Wind 5', foo: 3, bar: 3, baz: 4 } },
{ data: { id: 'Storage 1', foo: 3, bar: 3, baz: 4 } },
{ data: { id: 'Storage 2', foo: 3, bar: 3, baz: 4 } },
{ data: { id: 'Storage 3', foo: 3, bar: 3, baz: 4 } },
{ data: { id: 'Storage 4', foo: 3, bar: 3, baz: 4 } },
{ data: { id: 'Storage 5', foo: 3, bar: 3, baz: 4 } },
],
edges:[{ data: { id: 'link00', weight: 1, source: 'Storage 1', target: 'MainGrid' } },
{ data: { id: 'link01', weight: 1, source: 'Wind 2', target: 'MainGrid' } },
{ data: { id: 'link02', weight: 1, source: 'Wind 1', target: 'MainGrid' } },
{ data: { id: 'link03', weight: 1, source: 'Solar 3', target: 'MainGrid' } },
{ data: { id: 'link04', weight: 1, source: 'Storage 2', target: 'MainGrid' } },
{ data: { id: 'link05', weight: 1, source: 'Wind 4', target: 'MainGrid' } },
{ data: { id: 'link06', weight: 1, source: 'Wind 5', target: 'MainGrid' } },
{ data: { id: 'link07', weight: 1, source: 'Wind 3', target: 'MainGrid' } },
{ data: { id: 'link08', weight: 1, source: 'Solar 2', target: 'MainGrid' } },
{ data: { id: 'link09', weight: 1, source: 'Solar 1', target: 'MainGrid' } },
{ data: { id: 'link010', weight: 1, source: 'Storage 4', target: 'MainGrid' } },
{ data: { id: 'link011', weight: 1, source: 'Storage 3', target: 'MainGrid' } },
{ data: { id: 'link012', weight: 1, source: 'Storage 5', target: 'MainGrid' } },
{ data: { id: 'link10', weight: 1, source: 'Storage 1', target: 'Consumer 1' } },
{ data: { id: 'link11', weight: 1, source: 'Wind 2', target: 'Consumer 1' } },
{ data: { id: 'link12', weight: 1, source: 'Wind 1', target: 'Consumer 1' } },
{ data: { id: 'link13', weight: 1, source: 'Solar 3', target: 'Consumer 1' } },
{ data: { id: 'link14', weight: 1, source: 'Storage 2', target: 'Consumer 1' } },
{ data: { id: 'link15', weight: 1, source: 'Wind 4', target: 'Consumer 1' } },
{ data: { id: 'link16', weight: 1, source: 'Wind 5', target: 'Consumer 1' } },
{ data: { id: 'link17', weight: 1, source: 'Wind 3', target: 'Consumer 1' } },
{ data: { id: 'link18', weight: 1, source: 'Solar 2', target: 'Consumer 1' } },
{ data: { id: 'link19', weight: 1, source: 'Solar 1', target: 'Consumer 1' } },
{ data: { id: 'link110', weight: 1, source: 'Storage 4', target: 'Consumer 1' } },
{ data: { id: 'link111', weight: 1, source: 'Storage 3', target: 'Consumer 1' } },
{ data: { id: 'link112', weight: 1, source: 'Storage 5', target: 'Consumer 1' } },
{ data: { id: 'link113', weight: 1, source: 'MainGrid', target: 'Consumer 1' } },
{ data: { id: 'link20', weight: 1, source: 'Storage 1', target: 'Consumer 2' } },
{ data: { id: 'link21', weight: 1, source: 'Wind 2', target: 'Consumer 2' } },
{ data: { id: 'link22', weight: 1, source: 'Wind 1', target: 'Consumer 2' } },
{ data: { id: 'link23', weight: 1, source: 'Solar 3', target: 'Consumer 2' } },
{ data: { id: 'link24', weight: 1, source: 'Storage 2', target: 'Consumer 2' } },
{ data: { id: 'link25', weight: 1, source: 'Wind 4', target: 'Consumer 2' } },
{ data: { id: 'link26', weight: 1, source: 'Wind 5', target: 'Consumer 2' } },
{ data: { id: 'link27', weight: 1, source: 'Wind 3', target: 'Consumer 2' } },
{ data: { id: 'link28', weight: 1, source: 'Solar 2', target: 'Consumer 2' } },
{ data: { id: 'link29', weight: 1, source: 'Solar 1', target: 'Consumer 2' } },
{ data: { id: 'link210', weight: 1, source: 'Storage 4', target: 'Consumer 2' } },
{ data: { id: 'link211', weight: 1, source: 'Storage 3', target: 'Consumer 2' } },
{ data: { id: 'link212', weight: 1, source: 'Storage 5', target: 'Consumer 2' } },
{ data: { id: 'link213', weight: 1, source: 'MainGrid', target: 'Consumer 2' } },
{ data: { id: 'link30', weight: 1, source: 'Storage 1', target: 'Consumer 3' } },
{ data: { id: 'link31', weight: 1, source: 'Wind 2', target: 'Consumer 3' } },
{ data: { id: 'link32', weight: 1, source: 'Wind 1', target: 'Consumer 3' } },
{ data: { id: 'link33', weight: 1, source: 'Solar 3', target: 'Consumer 3' } },
{ data: { id: 'link34', weight: 1, source: 'Storage 2', target: 'Consumer 3' } },
{ data: { id: 'link35', weight: 1, source: 'Wind 4', target: 'Consumer 3' } },
{ data: { id: 'link36', weight: 1, source: 'Wind 5', target: 'Consumer 3' } },
{ data: { id: 'link37', weight: 1, source: 'Wind 3', target: 'Consumer 3' } },
{ data: { id: 'link38', weight: 1, source: 'Solar 2', target: 'Consumer 3' } },
{ data: { id: 'link39', weight: 1, source: 'Solar 1', target: 'Consumer 3' } },
{ data: { id: 'link310', weight: 1, source: 'Storage 4', target: 'Consumer 3' } },
{ data: { id: 'link311', weight: 1, source: 'Storage 3', target: 'Consumer 3' } },
{ data: { id: 'link312', weight: 1, source: 'Storage 5', target: 'Consumer 3' } },
{ data: { id: 'link313', weight: 1, source: 'MainGrid', target: 'Consumer 3' } },
{ data: { id: 'link40', weight: 1, source: 'Storage 1', target: 'Consumer 4' } },
{ data: { id: 'link41', weight: 1, source: 'Wind 2', target: 'Consumer 4' } },
{ data: { id: 'link42', weight: 1, source: 'Wind 1', target: 'Consumer 4' } },
{ data: { id: 'link43', weight: 1, source: 'Solar 3', target: 'Consumer 4' } },
{ data: { id: 'link44', weight: 1, source: 'Storage 2', target: 'Consumer 4' } },
{ data: { id: 'link45', weight: 1, source: 'Wind 4', target: 'Consumer 4' } },
{ data: { id: 'link46', weight: 1, source: 'Wind 5', target: 'Consumer 4' } },
{ data: { id: 'link47', weight: 1, source: 'Wind 3', target: 'Consumer 4' } },
{ data: { id: 'link48', weight: 1, source: 'Solar 2', target: 'Consumer 4' } },
{ data: { id: 'link49', weight: 1, source: 'Solar 1', target: 'Consumer 4' } },
{ data: { id: 'link410', weight: 1, source: 'Storage 4', target: 'Consumer 4' } },
{ data: { id: 'link411', weight: 1, source: 'Storage 3', target: 'Consumer 4' } },
{ data: { id: 'link412', weight: 1, source: 'Storage 5', target: 'Consumer 4' } },
{ data: { id: 'link413', weight: 1, source: 'MainGrid', target: 'Consumer 4' } },
{ data: { id: 'link50', weight: 1, source: 'Storage 1', target: 'Consumer 5' } },
{ data: { id: 'link51', weight: 1, source: 'Wind 2', target: 'Consumer 5' } },
{ data: { id: 'link52', weight: 1, source: 'Wind 1', target: 'Consumer 5' } },
{ data: { id: 'link53', weight: 1, source: 'Solar 3', target: 'Consumer 5' } },
{ data: { id: 'link54', weight: 1, source: 'Storage 2', target: 'Consumer 5' } },
{ data: { id: 'link55', weight: 1, source: 'Wind 4', target: 'Consumer 5' } },
{ data: { id: 'link56', weight: 1, source: 'Wind 5', target: 'Consumer 5' } },
{ data: { id: 'link57', weight: 1, source: 'Wind 3', target: 'Consumer 5' } },
{ data: { id: 'link58', weight: 1, source: 'Solar 2', target: 'Consumer 5' } },
{ data: { id: 'link59', weight: 1, source: 'Solar 1', target: 'Consumer 5' } },
{ data: { id: 'link510', weight: 1, source: 'Storage 4', target: 'Consumer 5' } },
{ data: { id: 'link511', weight: 1, source: 'Storage 3', target: 'Consumer 5' } },
{ data: { id: 'link512', weight: 1, source: 'Storage 5', target: 'Consumer 5' } },
{ data: { id: 'link513', weight: 1, source: 'MainGrid', target: 'Consumer 5' } },
{ data: { id: 'link140', weight: 1, source: 'Wind 2', target: 'Storage 1' } },
{ data: { id: 'link141', weight: 1, source: 'Wind 1', target: 'Storage 1' } },
{ data: { id: 'link142', weight: 1, source: 'Solar 3', target: 'Storage 1' } },
{ data: { id: 'link143', weight: 1, source: 'Wind 4', target: 'Storage 1' } },
{ data: { id: 'link144', weight: 1, source: 'Wind 5', target: 'Storage 1' } },
{ data: { id: 'link145', weight: 1, source: 'Wind 3', target: 'Storage 1' } },
{ data: { id: 'link146', weight: 1, source: 'Solar 2', target: 'Storage 1' } },
{ data: { id: 'link147', weight: 1, source: 'Solar 1', target: 'Storage 1' } },
{ data: { id: 'link148', weight: 1, source: 'MainGrid', target: 'Storage 1' } },
{ data: { id: 'link150', weight: 1, source: 'Wind 2', target: 'Storage 2' } },
{ data: { id: 'link151', weight: 1, source: 'Wind 1', target: 'Storage 2' } },
{ data: { id: 'link152', weight: 1, source: 'Solar 3', target: 'Storage 2' } },
{ data: { id: 'link153', weight: 1, source: 'Wind 4', target: 'Storage 2' } },
{ data: { id: 'link154', weight: 1, source: 'Wind 5', target: 'Storage 2' } },
{ data: { id: 'link155', weight: 1, source: 'Wind 3', target: 'Storage 2' } },
{ data: { id: 'link156', weight: 1, source: 'Solar 2', target: 'Storage 2' } },
{ data: { id: 'link157', weight: 1, source: 'Solar 1', target: 'Storage 2' } },
{ data: { id: 'link158', weight: 1, source: 'MainGrid', target: 'Storage 2' } },
{ data: { id: 'link160', weight: 1, source: 'Wind 2', target: 'Storage 3' } },
{ data: { id: 'link161', weight: 1, source: 'Wind 1', target: 'Storage 3' } },
{ data: { id: 'link162', weight: 1, source: 'Solar 3', target: 'Storage 3' } },
{ data: { id: 'link163', weight: 1, source: 'Wind 4', target: 'Storage 3' } },
{ data: { id: 'link164', weight: 1, source: 'Wind 5', target: 'Storage 3' } },
{ data: { id: 'link165', weight: 1, source: 'Wind 3', target: 'Storage 3' } },
{ data: { id: 'link166', weight: 1, source: 'Solar 2', target: 'Storage 3' } },
{ data: { id: 'link167', weight: 1, source: 'Solar 1', target: 'Storage 3' } },
{ data: { id: 'link168', weight: 1, source: 'MainGrid', target: 'Storage 3' } },
{ data: { id: 'link170', weight: 1, source: 'Wind 2', target: 'Storage 4' } },
{ data: { id: 'link171', weight: 1, source: 'Wind 1', target: 'Storage 4' } },
{ data: { id: 'link172', weight: 1, source: 'Solar 3', target: 'Storage 4' } },
{ data: { id: 'link173', weight: 1, source: 'Wind 4', target: 'Storage 4' } },
{ data: { id: 'link174', weight: 1, source: 'Wind 5', target: 'Storage 4' } },
{ data: { id: 'link175', weight: 1, source: 'Wind 3', target: 'Storage 4' } },
{ data: { id: 'link176', weight: 1, source: 'Solar 2', target: 'Storage 4' } },
{ data: { id: 'link177', weight: 1, source: 'Solar 1', target: 'Storage 4' } },
{ data: { id: 'link178', weight: 1, source: 'MainGrid', target: 'Storage 4' } },
{ data: { id: 'link180', weight: 1, source: 'Wind 2', target: 'Storage 5' } },
{ data: { id: 'link181', weight: 1, source: 'Wind 1', target: 'Storage 5' } },
{ data: { id: 'link182', weight: 1, source: 'Solar 3', target: 'Storage 5' } },
{ data: { id: 'link183', weight: 1, source: 'Wind 4', target: 'Storage 5' } },
{ data: { id: 'link184', weight: 1, source: 'Wind 5', target: 'Storage 5' } },
{ data: { id: 'link185', weight: 1, source: 'Wind 3', target: 'Storage 5' } },
{ data: { id: 'link186', weight: 1, source: 'Solar 2', target: 'Storage 5' } },
{ data: { id: 'link187', weight: 1, source: 'Solar 1', target: 'Storage 5' } },
{ data: { id: 'link188', weight: 1, source: 'MainGrid', target: 'Storage 5' } },
]},
layout: { /*ring, grid and*/ name: 'grid', padding: 10 } }); cy.on('tap', 'node', function(e){ var node = e.cyTarget; var neighborhood = node.neighborhood().add(node); cy.elements().addClass('faded'); neighborhood.removeClass('faded'); }); cy.on('tap', function(e){ if( e.cyTarget === cy ){ cy.elements().removeClass('faded'); } }); }); /* on dom ready*/
$( document ).ready(function() {$('#agentData tbody').append('<tr id="tidMainGrid"><td>MainGrid</td><td>$0.01</td><td>$1</td><td>$272.52</td><td>$26781.99</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 1"><td>Consumer 1</td><td>$0.99</td><td>$0.00</td><td>-$47.66</td><td>-$4731.38</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 2"><td>Consumer 2</td><td>$0.99</td><td>$0.00</td><td>-$47.69</td><td>-$4735.44</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 3"><td>Consumer 3</td><td>$0.99</td><td>$0.00</td><td>-$47.78</td><td>-$4741.09</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 4"><td>Consumer 4</td><td>$0.99</td><td>$0.00</td><td>-$47.76</td><td>-$4737.55</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 5"><td>Consumer 5</td><td>$0.99</td><td>$0.00</td><td>-$47.73</td><td>-$4741.77</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 1"><td>Solar 1</td><td>$0.00</td><td>$0.97</td><td>$8.51</td><td>$839.3</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 2"><td>Solar 2</td><td>$0.00</td><td>$0.97</td><td>$8.51</td><td>$839.36</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 3"><td>Solar 3</td><td>$0.00</td><td>$0.96</td><td>$9.38</td><td>$925.26</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 1"><td>Wind 1</td><td>$0.00</td><td>$0.96</td><td>$19.02</td><td>$1877.54</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 2"><td>Wind 2</td><td>$0.00</td><td>$0.96</td><td>$18.15</td><td>$1792.37</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 3"><td>Wind 3</td><td>$0.00</td><td>$0.97</td><td>$19.07</td><td>$1882.09</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 4"><td>Wind 4</td><td>$0.00</td><td>$0.97</td><td>$19.07</td><td>$1882.14</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 5"><td>Wind 5</td><td>$0.00</td><td>$0.97</td><td>$18.19</td><td>$1795.33</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 1"><td>Storage 1</td><td>$0.91</td><td>$0.91</td><td>$-29.83</td><td>$-2912</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 2"><td>Storage 2</td><td>$0.96</td><td>$0.96</td><td>$-29.9</td><td>$-2929.1</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 3"><td>Storage 3</td><td>$0.99</td><td>$0.99</td><td>$-28.81</td><td>$-2950.27</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 4"><td>Storage 4</td><td>$0.99</td><td>$0.99</td><td>$-31.4</td><td>$-3069.28</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 5"><td>Storage 5</td><td>$0.99</td><td>$0.99</td><td>$-33.87</td><td>$-3067.5</td></tr>');
});
