document.addEventListener('DOMContentLoaded', function(){ var cy = cytoscape({ container: document.querySelector('#cy'), boxSelectionEnabled: false, zoomingEnabled: false, panningEnabled: true, autounselectify: true, style: cytoscape.stylesheet() .selector('node') .css({ 'content': 'data(id)', width: '60px', height: '60px', 'text-valign': 'center', 'color': '#333', 'text-outline-width': 2, 'text-outline-color': 'white', 'pie-size': '80%', 'pie-1-background-color': '#E8747C', 'pie-1-background-size': 'mapData(red, 0, 10, 0, 100)', 'pie-2-background-color': '#74E883', 'pie-2-background-size': 'mapData(green, 0, 10, 0, 100)' }) .selector('edge') .css({ 'target-arrow-shape': 'triangle' }) .selector(':selected') .css({ 'background-color': 'black', 'line-color': 'black', 'target-arrow-color': 'green', 'source-arrow-color': 'green' }) .selector('.faded') .css({ 'opacity': 0.08, 'text-opacity': 0 }),
elements: {nodes:[{ data: { id: 'MainGrid', red: 5, green: 5 } },
{ data: { id: 'Consumer 1', red: 10, green: 0 } },
{ data: { id: 'Consumer 2', red: 10, green: 0 } },
{ data: { id: 'Consumer 3', red: 10, green: 0 } },
{ data: { id: 'Consumer 4', red: 10, green: 0 } },
{ data: { id: 'Consumer 5', red: 10, green: 0 } },
{ data: { id: 'Consumer 6', red: 10, green: 0 } },
{ data: { id: 'Consumer 7', red: 10, green: 0 } },
{ data: { id: 'Consumer 8', red: 10, green: 0 } },
{ data: { id: 'Consumer 9', red: 10, green: 0 } },
{ data: { id: 'Consumer 10', red: 10, green: 0 } },
{ data: { id: 'Consumer 11', red: 10, green: 0 } },
{ data: { id: 'Consumer 12', red: 10, green: 0 } },
{ data: { id: 'Consumer 13', red: 10, green: 0 } },
{ data: { id: 'Consumer 14', red: 10, green: 0 } },
{ data: { id: 'Consumer 15', red: 10, green: 0 } },
{ data: { id: 'Consumer 16', red: 10, green: 0 } },
{ data: { id: 'Consumer 17', red: 10, green: 0 } },
{ data: { id: 'Consumer 18', red: 10, green: 0 } },
{ data: { id: 'Consumer 19', red: 10, green: 0 } },
{ data: { id: 'Consumer 20', red: 10, green: 0 } },
{ data: { id: 'Solar 1', red: 0, green: 10 } },
{ data: { id: 'Solar 2', red: 0, green: 10 } },
{ data: { id: 'Solar 3', red: 0, green: 10 } },
{ data: { id: 'Solar 4', red: 0, green: 10 } },
{ data: { id: 'Solar 5', red: 0, green: 10 } },
{ data: { id: 'Solar 6', red: 0, green: 10 } },
{ data: { id: 'Solar 7', red: 0, green: 10 } },
{ data: { id: 'Solar 8', red: 0, green: 10 } },
{ data: { id: 'Solar 9', red: 0, green: 10 } },
{ data: { id: 'Solar 10', red: 0, green: 10 } },
{ data: { id: 'Wind 1', red: 0, green: 10 } },
{ data: { id: 'Wind 2', red: 0, green: 10 } },
{ data: { id: 'Wind 3', red: 0, green: 10 } },
{ data: { id: 'Wind 4', red: 0, green: 10 } },
{ data: { id: 'Wind 5', red: 0, green: 10 } },
{ data: { id: 'Wind 6', red: 0, green: 10 } },
{ data: { id: 'Wind 7', red: 0, green: 10 } },
{ data: { id: 'Wind 8', red: 0, green: 10 } },
{ data: { id: 'Wind 9', red: 0, green: 10 } },
{ data: { id: 'Wind 10', red: 0, green: 10 } },
{ data: { id: 'Storage 1', red: 5, green: 5 } },
{ data: { id: 'Storage 2', red: 5, green: 5 } },
{ data: { id: 'Storage 3', red: 5, green: 5 } },
{ data: { id: 'Storage 4', red: 5, green: 5 } },
{ data: { id: 'Storage 5', red: 5, green: 5 } },
{ data: { id: 'Storage 6', red: 5, green: 5 } },
{ data: { id: 'Storage 7', red: 5, green: 5 } },
{ data: { id: 'Storage 8', red: 5, green: 5 } },
{ data: { id: 'Storage 9', red: 5, green: 5 } },
{ data: { id: 'Storage 10', red: 5, green: 5 } },
{ data: { id: 'Storage 11', red: 5, green: 5 } },
{ data: { id: 'Storage 12', red: 5, green: 5 } },
{ data: { id: 'Storage 13', red: 5, green: 5 } },
{ data: { id: 'Storage 14', red: 5, green: 5 } },
{ data: { id: 'Storage 15', red: 5, green: 5 } },
{ data: { id: 'Storage 16', red: 5, green: 5 } },
{ data: { id: 'Storage 17', red: 5, green: 5 } },
{ data: { id: 'Storage 18', red: 5, green: 5 } },
{ data: { id: 'Storage 19', red: 5, green: 5 } },
{ data: { id: 'Storage 20', red: 5, green: 5 } },
],
edges:[{ data: { id: 'link00', weight: 1, source: 'Solar 7', target: 'MainGrid' } },
{ data: { id: 'link01', weight: 1, source: 'Solar 5', target: 'MainGrid' } },
{ data: { id: 'link02', weight: 1, source: 'Solar 4', target: 'MainGrid' } },
{ data: { id: 'link03', weight: 1, source: 'Solar 10', target: 'MainGrid' } },
{ data: { id: 'link04', weight: 1, source: 'Solar 8', target: 'MainGrid' } },
{ data: { id: 'link05', weight: 1, source: 'Solar 1', target: 'MainGrid' } },
{ data: { id: 'link06', weight: 1, source: 'Solar 2', target: 'MainGrid' } },
{ data: { id: 'link07', weight: 1, source: 'Solar 3', target: 'MainGrid' } },
{ data: { id: 'link08', weight: 1, source: 'Solar 6', target: 'MainGrid' } },
{ data: { id: 'link09', weight: 1, source: 'Solar 9', target: 'MainGrid' } },
{ data: { id: 'link010', weight: 1, source: 'Storage 17', target: 'MainGrid' } },
{ data: { id: 'link011', weight: 1, source: 'Storage 3', target: 'MainGrid' } },
{ data: { id: 'link012', weight: 1, source: 'Storage 12', target: 'MainGrid' } },
{ data: { id: 'link013', weight: 1, source: 'Storage 1', target: 'MainGrid' } },
{ data: { id: 'link014', weight: 1, source: 'Storage 18', target: 'MainGrid' } },
{ data: { id: 'link015', weight: 1, source: 'Storage 15', target: 'MainGrid' } },
{ data: { id: 'link016', weight: 1, source: 'Storage 6', target: 'MainGrid' } },
{ data: { id: 'link017', weight: 1, source: 'Storage 13', target: 'MainGrid' } },
{ data: { id: 'link018', weight: 1, source: 'Storage 16', target: 'MainGrid' } },
{ data: { id: 'link019', weight: 1, source: 'Storage 4', target: 'MainGrid' } },
{ data: { id: 'link020', weight: 1, source: 'Storage 11', target: 'MainGrid' } },
{ data: { id: 'link021', weight: 1, source: 'Storage 8', target: 'MainGrid' } },
{ data: { id: 'link022', weight: 1, source: 'Storage 5', target: 'MainGrid' } },
{ data: { id: 'link023', weight: 1, source: 'Storage 2', target: 'MainGrid' } },
{ data: { id: 'link024', weight: 1, source: 'Storage 7', target: 'MainGrid' } },
{ data: { id: 'link025', weight: 1, source: 'Storage 14', target: 'MainGrid' } },
{ data: { id: 'link026', weight: 1, source: 'Storage 19', target: 'MainGrid' } },
{ data: { id: 'link027', weight: 1, source: 'Storage 20', target: 'MainGrid' } },
{ data: { id: 'link028', weight: 1, source: 'Storage 10', target: 'MainGrid' } },
{ data: { id: 'link029', weight: 1, source: 'Storage 9', target: 'MainGrid' } },
{ data: { id: 'link030', weight: 1, source: 'Wind 4', target: 'MainGrid' } },
{ data: { id: 'link031', weight: 1, source: 'Wind 10', target: 'MainGrid' } },
{ data: { id: 'link032', weight: 1, source: 'Wind 2', target: 'MainGrid' } },
{ data: { id: 'link033', weight: 1, source: 'Wind 8', target: 'MainGrid' } },
{ data: { id: 'link034', weight: 1, source: 'Wind 5', target: 'MainGrid' } },
{ data: { id: 'link035', weight: 1, source: 'Wind 9', target: 'MainGrid' } },
{ data: { id: 'link036', weight: 1, source: 'Wind 3', target: 'MainGrid' } },
{ data: { id: 'link037', weight: 1, source: 'Wind 7', target: 'MainGrid' } },
{ data: { id: 'link038', weight: 1, source: 'Wind 6', target: 'MainGrid' } },
{ data: { id: 'link039', weight: 1, source: 'Wind 1', target: 'MainGrid' } },
{ data: { id: 'link10', weight: 1, source: 'Solar 4', target: 'Consumer 1' } },
{ data: { id: 'link11', weight: 1, source: 'Solar 1', target: 'Consumer 1' } },
{ data: { id: 'link12', weight: 1, source: 'Solar 2', target: 'Consumer 1' } },
{ data: { id: 'link13', weight: 1, source: 'Solar 3', target: 'Consumer 1' } },
{ data: { id: 'link14', weight: 1, source: 'Solar 6', target: 'Consumer 1' } },
{ data: { id: 'link15', weight: 1, source: 'Storage 3', target: 'Consumer 1' } },
{ data: { id: 'link16', weight: 1, source: 'Storage 1', target: 'Consumer 1' } },
{ data: { id: 'link17', weight: 1, source: 'Storage 6', target: 'Consumer 1' } },
{ data: { id: 'link18', weight: 1, source: 'Storage 16', target: 'Consumer 1' } },
{ data: { id: 'link19', weight: 1, source: 'Storage 4', target: 'Consumer 1' } },
{ data: { id: 'link110', weight: 1, source: 'Storage 11', target: 'Consumer 1' } },
{ data: { id: 'link111', weight: 1, source: 'Storage 2', target: 'Consumer 1' } },
{ data: { id: 'link112', weight: 1, source: 'MainGrid', target: 'Consumer 1' } },
{ data: { id: 'link113', weight: 1, source: 'Wind 1', target: 'Consumer 1' } },
{ data: { id: 'link114', weight: 1, source: 'Wind 6', target: 'Consumer 1' } },
{ data: { id: 'link20', weight: 1, source: 'Solar 7', target: 'Consumer 2' } },
{ data: { id: 'link21', weight: 1, source: 'Solar 5', target: 'Consumer 2' } },
{ data: { id: 'link22', weight: 1, source: 'Solar 8', target: 'Consumer 2' } },
{ data: { id: 'link23', weight: 1, source: 'Solar 1', target: 'Consumer 2' } },
{ data: { id: 'link24', weight: 1, source: 'Solar 6', target: 'Consumer 2' } },
{ data: { id: 'link25', weight: 1, source: 'Storage 1', target: 'Consumer 2' } },
{ data: { id: 'link26', weight: 1, source: 'Storage 6', target: 'Consumer 2' } },
{ data: { id: 'link27', weight: 1, source: 'Storage 16', target: 'Consumer 2' } },
{ data: { id: 'link28', weight: 1, source: 'Storage 11', target: 'Consumer 2' } },
{ data: { id: 'link29', weight: 1, source: 'Storage 8', target: 'Consumer 2' } },
{ data: { id: 'link210', weight: 1, source: 'Storage 5', target: 'Consumer 2' } },
{ data: { id: 'link211', weight: 1, source: 'Storage 7', target: 'Consumer 2' } },
{ data: { id: 'link212', weight: 1, source: 'MainGrid', target: 'Consumer 2' } },
{ data: { id: 'link213', weight: 1, source: 'Wind 1', target: 'Consumer 2' } },
{ data: { id: 'link214', weight: 1, source: 'Wind 6', target: 'Consumer 2' } },
{ data: { id: 'link30', weight: 1, source: 'Solar 10', target: 'Consumer 3' } },
{ data: { id: 'link31', weight: 1, source: 'Solar 1', target: 'Consumer 3' } },
{ data: { id: 'link32', weight: 1, source: 'Solar 6', target: 'Consumer 3' } },
{ data: { id: 'link33', weight: 1, source: 'Solar 9', target: 'Consumer 3' } },
{ data: { id: 'link34', weight: 1, source: 'Storage 12', target: 'Consumer 3' } },
{ data: { id: 'link35', weight: 1, source: 'Storage 1', target: 'Consumer 3' } },
{ data: { id: 'link36', weight: 1, source: 'Storage 6', target: 'Consumer 3' } },
{ data: { id: 'link37', weight: 1, source: 'Storage 16', target: 'Consumer 3' } },
{ data: { id: 'link38', weight: 1, source: 'Storage 11', target: 'Consumer 3' } },
{ data: { id: 'link39', weight: 1, source: 'Storage 10', target: 'Consumer 3' } },
{ data: { id: 'link310', weight: 1, source: 'Storage 9', target: 'Consumer 3' } },
{ data: { id: 'link311', weight: 1, source: 'MainGrid', target: 'Consumer 3' } },
{ data: { id: 'link312', weight: 1, source: 'Wind 6', target: 'Consumer 3' } },
{ data: { id: 'link313', weight: 1, source: 'Wind 2', target: 'Consumer 3' } },
{ data: { id: 'link314', weight: 1, source: 'Wind 1', target: 'Consumer 3' } },
{ data: { id: 'link40', weight: 1, source: 'Solar 1', target: 'Consumer 4' } },
{ data: { id: 'link41', weight: 1, source: 'Solar 6', target: 'Consumer 4' } },
{ data: { id: 'link42', weight: 1, source: 'Storage 1', target: 'Consumer 4' } },
{ data: { id: 'link43', weight: 1, source: 'Storage 15', target: 'Consumer 4' } },
{ data: { id: 'link44', weight: 1, source: 'Storage 6', target: 'Consumer 4' } },
{ data: { id: 'link45', weight: 1, source: 'Storage 13', target: 'Consumer 4' } },
{ data: { id: 'link46', weight: 1, source: 'Storage 16', target: 'Consumer 4' } },
{ data: { id: 'link47', weight: 1, source: 'Storage 11', target: 'Consumer 4' } },
{ data: { id: 'link48', weight: 1, source: 'Storage 14', target: 'Consumer 4' } },
{ data: { id: 'link49', weight: 1, source: 'MainGrid', target: 'Consumer 4' } },
{ data: { id: 'link410', weight: 1, source: 'Wind 4', target: 'Consumer 4' } },
{ data: { id: 'link411', weight: 1, source: 'Wind 1', target: 'Consumer 4' } },
{ data: { id: 'link412', weight: 1, source: 'Wind 3', target: 'Consumer 4' } },
{ data: { id: 'link413', weight: 1, source: 'Wind 5', target: 'Consumer 4' } },
{ data: { id: 'link414', weight: 1, source: 'Wind 6', target: 'Consumer 4' } },
{ data: { id: 'link50', weight: 1, source: 'Solar 7', target: 'Consumer 5' } },
{ data: { id: 'link51', weight: 1, source: 'Solar 2', target: 'Consumer 5' } },
{ data: { id: 'link52', weight: 1, source: 'Storage 17', target: 'Consumer 5' } },
{ data: { id: 'link53', weight: 1, source: 'Storage 12', target: 'Consumer 5' } },
{ data: { id: 'link54', weight: 1, source: 'Storage 18', target: 'Consumer 5' } },
{ data: { id: 'link55', weight: 1, source: 'Storage 2', target: 'Consumer 5' } },
{ data: { id: 'link56', weight: 1, source: 'Storage 7', target: 'Consumer 5' } },
{ data: { id: 'link57', weight: 1, source: 'Storage 19', target: 'Consumer 5' } },
{ data: { id: 'link58', weight: 1, source: 'Storage 20', target: 'Consumer 5' } },
{ data: { id: 'link59', weight: 1, source: 'MainGrid', target: 'Consumer 5' } },
{ data: { id: 'link510', weight: 1, source: 'Wind 2', target: 'Consumer 5' } },
{ data: { id: 'link511', weight: 1, source: 'Wind 9', target: 'Consumer 5' } },
{ data: { id: 'link512', weight: 1, source: 'Wind 7', target: 'Consumer 5' } },
{ data: { id: 'link513', weight: 1, source: 'Wind 8', target: 'Consumer 5' } },
{ data: { id: 'link514', weight: 1, source: 'Wind 10', target: 'Consumer 5' } },
{ data: { id: 'link60', weight: 1, source: 'Solar 7', target: 'Consumer 6' } },
{ data: { id: 'link61', weight: 1, source: 'Solar 4', target: 'Consumer 6' } },
{ data: { id: 'link62', weight: 1, source: 'Solar 1', target: 'Consumer 6' } },
{ data: { id: 'link63', weight: 1, source: 'Solar 2', target: 'Consumer 6' } },
{ data: { id: 'link64', weight: 1, source: 'Solar 3', target: 'Consumer 6' } },
{ data: { id: 'link65', weight: 1, source: 'Storage 17', target: 'Consumer 6' } },
{ data: { id: 'link66', weight: 1, source: 'Storage 3', target: 'Consumer 6' } },
{ data: { id: 'link67', weight: 1, source: 'Storage 12', target: 'Consumer 6' } },
{ data: { id: 'link68', weight: 1, source: 'Storage 1', target: 'Consumer 6' } },
{ data: { id: 'link69', weight: 1, source: 'Storage 4', target: 'Consumer 6' } },
{ data: { id: 'link610', weight: 1, source: 'Storage 2', target: 'Consumer 6' } },
{ data: { id: 'link611', weight: 1, source: 'Storage 7', target: 'Consumer 6' } },
{ data: { id: 'link612', weight: 1, source: 'MainGrid', target: 'Consumer 6' } },
{ data: { id: 'link613', weight: 1, source: 'Wind 2', target: 'Consumer 6' } },
{ data: { id: 'link614', weight: 1, source: 'Wind 7', target: 'Consumer 6' } },
{ data: { id: 'link70', weight: 1, source: 'Solar 7', target: 'Consumer 7' } },
{ data: { id: 'link71', weight: 1, source: 'Solar 5', target: 'Consumer 7' } },
{ data: { id: 'link72', weight: 1, source: 'Solar 8', target: 'Consumer 7' } },
{ data: { id: 'link73', weight: 1, source: 'Solar 2', target: 'Consumer 7' } },
{ data: { id: 'link74', weight: 1, source: 'Solar 6', target: 'Consumer 7' } },
{ data: { id: 'link75', weight: 1, source: 'Storage 17', target: 'Consumer 7' } },
{ data: { id: 'link76', weight: 1, source: 'Storage 12', target: 'Consumer 7' } },
{ data: { id: 'link77', weight: 1, source: 'Storage 6', target: 'Consumer 7' } },
{ data: { id: 'link78', weight: 1, source: 'Storage 8', target: 'Consumer 7' } },
{ data: { id: 'link79', weight: 1, source: 'Storage 5', target: 'Consumer 7' } },
{ data: { id: 'link710', weight: 1, source: 'Storage 2', target: 'Consumer 7' } },
{ data: { id: 'link711', weight: 1, source: 'Storage 7', target: 'Consumer 7' } },
{ data: { id: 'link712', weight: 1, source: 'MainGrid', target: 'Consumer 7' } },
{ data: { id: 'link713', weight: 1, source: 'Wind 2', target: 'Consumer 7' } },
{ data: { id: 'link714', weight: 1, source: 'Wind 7', target: 'Consumer 7' } },
{ data: { id: 'link80', weight: 1, source: 'Solar 7', target: 'Consumer 8' } },
{ data: { id: 'link81', weight: 1, source: 'Solar 10', target: 'Consumer 8' } },
{ data: { id: 'link82', weight: 1, source: 'Solar 2', target: 'Consumer 8' } },
{ data: { id: 'link83', weight: 1, source: 'Solar 9', target: 'Consumer 8' } },
{ data: { id: 'link84', weight: 1, source: 'Storage 17', target: 'Consumer 8' } },
{ data: { id: 'link85', weight: 1, source: 'Storage 12', target: 'Consumer 8' } },
{ data: { id: 'link86', weight: 1, source: 'Storage 11', target: 'Consumer 8' } },
{ data: { id: 'link87', weight: 1, source: 'Storage 2', target: 'Consumer 8' } },
{ data: { id: 'link88', weight: 1, source: 'Storage 7', target: 'Consumer 8' } },
{ data: { id: 'link89', weight: 1, source: 'Storage 10', target: 'Consumer 8' } },
{ data: { id: 'link810', weight: 1, source: 'Storage 9', target: 'Consumer 8' } },
{ data: { id: 'link811', weight: 1, source: 'MainGrid', target: 'Consumer 8' } },
{ data: { id: 'link812', weight: 1, source: 'Wind 7', target: 'Consumer 8' } },
{ data: { id: 'link813', weight: 1, source: 'Wind 2', target: 'Consumer 8' } },
{ data: { id: 'link814', weight: 1, source: 'Wind 1', target: 'Consumer 8' } },
{ data: { id: 'link90', weight: 1, source: 'Solar 8', target: 'Consumer 9' } },
{ data: { id: 'link91', weight: 1, source: 'Solar 3', target: 'Consumer 9' } },
{ data: { id: 'link92', weight: 1, source: 'Storage 3', target: 'Consumer 9' } },
{ data: { id: 'link93', weight: 1, source: 'Storage 18', target: 'Consumer 9' } },
{ data: { id: 'link94', weight: 1, source: 'Storage 15', target: 'Consumer 9' } },
{ data: { id: 'link95', weight: 1, source: 'Storage 13', target: 'Consumer 9' } },
{ data: { id: 'link96', weight: 1, source: 'Storage 16', target: 'Consumer 9' } },
{ data: { id: 'link97', weight: 1, source: 'Storage 8', target: 'Consumer 9' } },
{ data: { id: 'link98', weight: 1, source: 'Storage 14', target: 'Consumer 9' } },
{ data: { id: 'link99', weight: 1, source: 'MainGrid', target: 'Consumer 9' } },
{ data: { id: 'link910', weight: 1, source: 'Wind 5', target: 'Consumer 9' } },
{ data: { id: 'link911', weight: 1, source: 'Wind 4', target: 'Consumer 9' } },
{ data: { id: 'link912', weight: 1, source: 'Wind 8', target: 'Consumer 9' } },
{ data: { id: 'link913', weight: 1, source: 'Wind 6', target: 'Consumer 9' } },
{ data: { id: 'link914', weight: 1, source: 'Wind 3', target: 'Consumer 9' } },
{ data: { id: 'link100', weight: 1, source: 'Solar 8', target: 'Consumer 10' } },
{ data: { id: 'link101', weight: 1, source: 'Solar 3', target: 'Consumer 10' } },
{ data: { id: 'link102', weight: 1, source: 'Storage 17', target: 'Consumer 10' } },
{ data: { id: 'link103', weight: 1, source: 'Storage 3', target: 'Consumer 10' } },
{ data: { id: 'link104', weight: 1, source: 'Storage 18', target: 'Consumer 10' } },
{ data: { id: 'link105', weight: 1, source: 'Storage 13', target: 'Consumer 10' } },
{ data: { id: 'link106', weight: 1, source: 'Storage 8', target: 'Consumer 10' } },
{ data: { id: 'link107', weight: 1, source: 'Storage 19', target: 'Consumer 10' } },
{ data: { id: 'link108', weight: 1, source: 'Storage 20', target: 'Consumer 10' } },
{ data: { id: 'link109', weight: 1, source: 'MainGrid', target: 'Consumer 10' } },
{ data: { id: 'link1010', weight: 1, source: 'Wind 8', target: 'Consumer 10' } },
{ data: { id: 'link1011', weight: 1, source: 'Wind 3', target: 'Consumer 10' } },
{ data: { id: 'link1012', weight: 1, source: 'Wind 10', target: 'Consumer 10' } },
{ data: { id: 'link1013', weight: 1, source: 'Wind 9', target: 'Consumer 10' } },
{ data: { id: 'link1014', weight: 1, source: 'Wind 7', target: 'Consumer 10' } },
{ data: { id: 'link110', weight: 1, source: 'Solar 4', target: 'Consumer 11' } },
{ data: { id: 'link111', weight: 1, source: 'Solar 8', target: 'Consumer 11' } },
{ data: { id: 'link112', weight: 1, source: 'Solar 1', target: 'Consumer 11' } },
{ data: { id: 'link113', weight: 1, source: 'Solar 2', target: 'Consumer 11' } },
{ data: { id: 'link114', weight: 1, source: 'Solar 3', target: 'Consumer 11' } },
{ data: { id: 'link115', weight: 1, source: 'Storage 3', target: 'Consumer 11' } },
{ data: { id: 'link116', weight: 1, source: 'Storage 1', target: 'Consumer 11' } },
{ data: { id: 'link117', weight: 1, source: 'Storage 18', target: 'Consumer 11' } },
{ data: { id: 'link118', weight: 1, source: 'Storage 13', target: 'Consumer 11' } },
{ data: { id: 'link119', weight: 1, source: 'Storage 4', target: 'Consumer 11' } },
{ data: { id: 'link1110', weight: 1, source: 'Storage 8', target: 'Consumer 11' } },
{ data: { id: 'link1111', weight: 1, source: 'Storage 2', target: 'Consumer 11' } },
{ data: { id: 'link1112', weight: 1, source: 'MainGrid', target: 'Consumer 11' } },
{ data: { id: 'link1113', weight: 1, source: 'Wind 3', target: 'Consumer 11' } },
{ data: { id: 'link1114', weight: 1, source: 'Wind 8', target: 'Consumer 11' } },
{ data: { id: 'link120', weight: 1, source: 'Solar 7', target: 'Consumer 12' } },
{ data: { id: 'link121', weight: 1, source: 'Solar 5', target: 'Consumer 12' } },
{ data: { id: 'link122', weight: 1, source: 'Solar 8', target: 'Consumer 12' } },
{ data: { id: 'link123', weight: 1, source: 'Solar 3', target: 'Consumer 12' } },
{ data: { id: 'link124', weight: 1, source: 'Solar 6', target: 'Consumer 12' } },
{ data: { id: 'link125', weight: 1, source: 'Storage 3', target: 'Consumer 12' } },
{ data: { id: 'link126', weight: 1, source: 'Storage 18', target: 'Consumer 12' } },
{ data: { id: 'link127', weight: 1, source: 'Storage 6', target: 'Consumer 12' } },
{ data: { id: 'link128', weight: 1, source: 'Storage 13', target: 'Consumer 12' } },
{ data: { id: 'link129', weight: 1, source: 'Storage 8', target: 'Consumer 12' } },
{ data: { id: 'link1210', weight: 1, source: 'Storage 5', target: 'Consumer 12' } },
{ data: { id: 'link1211', weight: 1, source: 'Storage 7', target: 'Consumer 12' } },
{ data: { id: 'link1212', weight: 1, source: 'MainGrid', target: 'Consumer 12' } },
{ data: { id: 'link1213', weight: 1, source: 'Wind 8', target: 'Consumer 12' } },
{ data: { id: 'link1214', weight: 1, source: 'Wind 3', target: 'Consumer 12' } },
{ data: { id: 'link130', weight: 1, source: 'Solar 4', target: 'Consumer 13' } },
{ data: { id: 'link131', weight: 1, source: 'Solar 10', target: 'Consumer 13' } },
{ data: { id: 'link132', weight: 1, source: 'Solar 9', target: 'Consumer 13' } },
{ data: { id: 'link133', weight: 1, source: 'Storage 12', target: 'Consumer 13' } },
{ data: { id: 'link134', weight: 1, source: 'Storage 4', target: 'Consumer 13' } },
{ data: { id: 'link135', weight: 1, source: 'Storage 11', target: 'Consumer 13' } },
{ data: { id: 'link136', weight: 1, source: 'Storage 14', target: 'Consumer 13' } },
{ data: { id: 'link137', weight: 1, source: 'Storage 19', target: 'Consumer 13' } },
{ data: { id: 'link138', weight: 1, source: 'Storage 10', target: 'Consumer 13' } },
{ data: { id: 'link139', weight: 1, source: 'Storage 9', target: 'Consumer 13' } },
{ data: { id: 'link1310', weight: 1, source: 'MainGrid', target: 'Consumer 13' } },
{ data: { id: 'link1311', weight: 1, source: 'Wind 9', target: 'Consumer 13' } },
{ data: { id: 'link1312', weight: 1, source: 'Wind 2', target: 'Consumer 13' } },
{ data: { id: 'link1313', weight: 1, source: 'Wind 4', target: 'Consumer 13' } },
{ data: { id: 'link1314', weight: 1, source: 'Wind 1', target: 'Consumer 13' } },
{ data: { id: 'link140', weight: 1, source: 'Solar 4', target: 'Consumer 14' } },
{ data: { id: 'link141', weight: 1, source: 'Solar 9', target: 'Consumer 14' } },
{ data: { id: 'link142', weight: 1, source: 'Storage 15', target: 'Consumer 14' } },
{ data: { id: 'link143', weight: 1, source: 'Storage 13', target: 'Consumer 14' } },
{ data: { id: 'link144', weight: 1, source: 'Storage 16', target: 'Consumer 14' } },
{ data: { id: 'link145', weight: 1, source: 'Storage 4', target: 'Consumer 14' } },
{ data: { id: 'link146', weight: 1, source: 'Storage 14', target: 'Consumer 14' } },
{ data: { id: 'link147', weight: 1, source: 'Storage 19', target: 'Consumer 14' } },
{ data: { id: 'link148', weight: 1, source: 'Storage 9', target: 'Consumer 14' } },
{ data: { id: 'link149', weight: 1, source: 'MainGrid', target: 'Consumer 14' } },
{ data: { id: 'link1410', weight: 1, source: 'Wind 9', target: 'Consumer 14' } },
{ data: { id: 'link1411', weight: 1, source: 'Wind 5', target: 'Consumer 14' } },
{ data: { id: 'link1412', weight: 1, source: 'Wind 3', target: 'Consumer 14' } },
{ data: { id: 'link1413', weight: 1, source: 'Wind 6', target: 'Consumer 14' } },
{ data: { id: 'link1414', weight: 1, source: 'Wind 4', target: 'Consumer 14' } },
{ data: { id: 'link150', weight: 1, source: 'Solar 4', target: 'Consumer 15' } },
{ data: { id: 'link151', weight: 1, source: 'Solar 9', target: 'Consumer 15' } },
{ data: { id: 'link152', weight: 1, source: 'Storage 17', target: 'Consumer 15' } },
{ data: { id: 'link153', weight: 1, source: 'Storage 18', target: 'Consumer 15' } },
{ data: { id: 'link154', weight: 1, source: 'Storage 4', target: 'Consumer 15' } },
{ data: { id: 'link155', weight: 1, source: 'Storage 14', target: 'Consumer 15' } },
{ data: { id: 'link156', weight: 1, source: 'Storage 19', target: 'Consumer 15' } },
{ data: { id: 'link157', weight: 1, source: 'Storage 20', target: 'Consumer 15' } },
{ data: { id: 'link158', weight: 1, source: 'Storage 9', target: 'Consumer 15' } },
{ data: { id: 'link159', weight: 1, source: 'MainGrid', target: 'Consumer 15' } },
{ data: { id: 'link1510', weight: 1, source: 'Wind 4', target: 'Consumer 15' } },
{ data: { id: 'link1511', weight: 1, source: 'Wind 8', target: 'Consumer 15' } },
{ data: { id: 'link1512', weight: 1, source: 'Wind 7', target: 'Consumer 15' } },
{ data: { id: 'link1513', weight: 1, source: 'Wind 9', target: 'Consumer 15' } },
{ data: { id: 'link1514', weight: 1, source: 'Wind 10', target: 'Consumer 15' } },
{ data: { id: 'link160', weight: 1, source: 'Solar 4', target: 'Consumer 16' } },
{ data: { id: 'link161', weight: 1, source: 'Solar 1', target: 'Consumer 16' } },
{ data: { id: 'link162', weight: 1, source: 'Solar 2', target: 'Consumer 16' } },
{ data: { id: 'link163', weight: 1, source: 'Solar 3', target: 'Consumer 16' } },
{ data: { id: 'link164', weight: 1, source: 'Solar 9', target: 'Consumer 16' } },
{ data: { id: 'link165', weight: 1, source: 'Storage 3', target: 'Consumer 16' } },
{ data: { id: 'link166', weight: 1, source: 'Storage 1', target: 'Consumer 16' } },
{ data: { id: 'link167', weight: 1, source: 'Storage 4', target: 'Consumer 16' } },
{ data: { id: 'link168', weight: 1, source: 'Storage 2', target: 'Consumer 16' } },
{ data: { id: 'link169', weight: 1, source: 'Storage 14', target: 'Consumer 16' } },
{ data: { id: 'link1610', weight: 1, source: 'Storage 19', target: 'Consumer 16' } },
{ data: { id: 'link1611', weight: 1, source: 'Storage 9', target: 'Consumer 16' } },
{ data: { id: 'link1612', weight: 1, source: 'MainGrid', target: 'Consumer 16' } },
{ data: { id: 'link1613', weight: 1, source: 'Wind 9', target: 'Consumer 16' } },
{ data: { id: 'link1614', weight: 1, source: 'Wind 4', target: 'Consumer 16' } },
{ data: { id: 'link170', weight: 1, source: 'Solar 7', target: 'Consumer 17' } },
{ data: { id: 'link171', weight: 1, source: 'Solar 5', target: 'Consumer 17' } },
{ data: { id: 'link172', weight: 1, source: 'Solar 10', target: 'Consumer 17' } },
{ data: { id: 'link173', weight: 1, source: 'Solar 8', target: 'Consumer 17' } },
{ data: { id: 'link174', weight: 1, source: 'Solar 6', target: 'Consumer 17' } },
{ data: { id: 'link175', weight: 1, source: 'Storage 15', target: 'Consumer 17' } },
{ data: { id: 'link176', weight: 1, source: 'Storage 6', target: 'Consumer 17' } },
{ data: { id: 'link177', weight: 1, source: 'Storage 8', target: 'Consumer 17' } },
{ data: { id: 'link178', weight: 1, source: 'Storage 5', target: 'Consumer 17' } },
{ data: { id: 'link179', weight: 1, source: 'Storage 7', target: 'Consumer 17' } },
{ data: { id: 'link1710', weight: 1, source: 'Storage 20', target: 'Consumer 17' } },
{ data: { id: 'link1711', weight: 1, source: 'Storage 10', target: 'Consumer 17' } },
{ data: { id: 'link1712', weight: 1, source: 'MainGrid', target: 'Consumer 17' } },
{ data: { id: 'link1713', weight: 1, source: 'Wind 10', target: 'Consumer 17' } },
{ data: { id: 'link1714', weight: 1, source: 'Wind 5', target: 'Consumer 17' } },
{ data: { id: 'link180', weight: 1, source: 'Solar 5', target: 'Consumer 18' } },
{ data: { id: 'link181', weight: 1, source: 'Solar 10', target: 'Consumer 18' } },
{ data: { id: 'link182', weight: 1, source: 'Solar 9', target: 'Consumer 18' } },
{ data: { id: 'link183', weight: 1, source: 'Storage 12', target: 'Consumer 18' } },
{ data: { id: 'link184', weight: 1, source: 'Storage 15', target: 'Consumer 18' } },
{ data: { id: 'link185', weight: 1, source: 'Storage 11', target: 'Consumer 18' } },
{ data: { id: 'link186', weight: 1, source: 'Storage 5', target: 'Consumer 18' } },
{ data: { id: 'link187', weight: 1, source: 'Storage 20', target: 'Consumer 18' } },
{ data: { id: 'link188', weight: 1, source: 'Storage 10', target: 'Consumer 18' } },
{ data: { id: 'link189', weight: 1, source: 'Storage 9', target: 'Consumer 18' } },
{ data: { id: 'link1810', weight: 1, source: 'MainGrid', target: 'Consumer 18' } },
{ data: { id: 'link1811', weight: 1, source: 'Wind 5', target: 'Consumer 18' } },
{ data: { id: 'link1812', weight: 1, source: 'Wind 10', target: 'Consumer 18' } },
{ data: { id: 'link1813', weight: 1, source: 'Wind 2', target: 'Consumer 18' } },
{ data: { id: 'link1814', weight: 1, source: 'Wind 1', target: 'Consumer 18' } },
{ data: { id: 'link190', weight: 1, source: 'Solar 5', target: 'Consumer 19' } },
{ data: { id: 'link191', weight: 1, source: 'Solar 10', target: 'Consumer 19' } },
{ data: { id: 'link192', weight: 1, source: 'Storage 15', target: 'Consumer 19' } },
{ data: { id: 'link193', weight: 1, source: 'Storage 13', target: 'Consumer 19' } },
{ data: { id: 'link194', weight: 1, source: 'Storage 16', target: 'Consumer 19' } },
{ data: { id: 'link195', weight: 1, source: 'Storage 5', target: 'Consumer 19' } },
{ data: { id: 'link196', weight: 1, source: 'Storage 14', target: 'Consumer 19' } },
{ data: { id: 'link197', weight: 1, source: 'Storage 20', target: 'Consumer 19' } },
{ data: { id: 'link198', weight: 1, source: 'Storage 10', target: 'Consumer 19' } },
{ data: { id: 'link199', weight: 1, source: 'MainGrid', target: 'Consumer 19' } },
{ data: { id: 'link1910', weight: 1, source: 'Wind 10', target: 'Consumer 19' } },
{ data: { id: 'link1911', weight: 1, source: 'Wind 5', target: 'Consumer 19' } },
{ data: { id: 'link1912', weight: 1, source: 'Wind 6', target: 'Consumer 19' } },
{ data: { id: 'link1913', weight: 1, source: 'Wind 3', target: 'Consumer 19' } },
{ data: { id: 'link1914', weight: 1, source: 'Wind 4', target: 'Consumer 19' } },
{ data: { id: 'link200', weight: 1, source: 'Solar 5', target: 'Consumer 20' } },
{ data: { id: 'link201', weight: 1, source: 'Solar 10', target: 'Consumer 20' } },
{ data: { id: 'link202', weight: 1, source: 'Storage 17', target: 'Consumer 20' } },
{ data: { id: 'link203', weight: 1, source: 'Storage 18', target: 'Consumer 20' } },
{ data: { id: 'link204', weight: 1, source: 'Storage 15', target: 'Consumer 20' } },
{ data: { id: 'link205', weight: 1, source: 'Storage 5', target: 'Consumer 20' } },
{ data: { id: 'link206', weight: 1, source: 'Storage 19', target: 'Consumer 20' } },
{ data: { id: 'link207', weight: 1, source: 'Storage 20', target: 'Consumer 20' } },
{ data: { id: 'link208', weight: 1, source: 'Storage 10', target: 'Consumer 20' } },
{ data: { id: 'link209', weight: 1, source: 'MainGrid', target: 'Consumer 20' } },
{ data: { id: 'link2010', weight: 1, source: 'Wind 10', target: 'Consumer 20' } },
{ data: { id: 'link2011', weight: 1, source: 'Wind 9', target: 'Consumer 20' } },
{ data: { id: 'link2012', weight: 1, source: 'Wind 5', target: 'Consumer 20' } },
{ data: { id: 'link2013', weight: 1, source: 'Wind 7', target: 'Consumer 20' } },
{ data: { id: 'link2014', weight: 1, source: 'Wind 8', target: 'Consumer 20' } },
{ data: { id: 'link410', weight: 1, source: 'Solar 4', target: 'Storage 1' } },
{ data: { id: 'link411', weight: 1, source: 'Solar 1', target: 'Storage 1' } },
{ data: { id: 'link412', weight: 1, source: 'Solar 2', target: 'Storage 1' } },
{ data: { id: 'link413', weight: 1, source: 'Solar 3', target: 'Storage 1' } },
{ data: { id: 'link414', weight: 1, source: 'Solar 6', target: 'Storage 1' } },
{ data: { id: 'link415', weight: 1, source: 'MainGrid', target: 'Storage 1' } },
{ data: { id: 'link416', weight: 1, source: 'Wind 6', target: 'Storage 1' } },
{ data: { id: 'link417', weight: 1, source: 'Wind 1', target: 'Storage 1' } },
{ data: { id: 'link420', weight: 1, source: 'Solar 7', target: 'Storage 2' } },
{ data: { id: 'link421', weight: 1, source: 'Solar 5', target: 'Storage 2' } },
{ data: { id: 'link422', weight: 1, source: 'Solar 8', target: 'Storage 2' } },
{ data: { id: 'link423', weight: 1, source: 'Solar 1', target: 'Storage 2' } },
{ data: { id: 'link424', weight: 1, source: 'Solar 6', target: 'Storage 2' } },
{ data: { id: 'link425', weight: 1, source: 'MainGrid', target: 'Storage 2' } },
{ data: { id: 'link426', weight: 1, source: 'Wind 1', target: 'Storage 2' } },
{ data: { id: 'link427', weight: 1, source: 'Wind 6', target: 'Storage 2' } },
{ data: { id: 'link430', weight: 1, source: 'Solar 10', target: 'Storage 3' } },
{ data: { id: 'link431', weight: 1, source: 'Solar 1', target: 'Storage 3' } },
{ data: { id: 'link432', weight: 1, source: 'Solar 6', target: 'Storage 3' } },
{ data: { id: 'link433', weight: 1, source: 'Solar 9', target: 'Storage 3' } },
{ data: { id: 'link434', weight: 1, source: 'MainGrid', target: 'Storage 3' } },
{ data: { id: 'link435', weight: 1, source: 'Wind 1', target: 'Storage 3' } },
{ data: { id: 'link436', weight: 1, source: 'Wind 6', target: 'Storage 3' } },
{ data: { id: 'link437', weight: 1, source: 'Wind 2', target: 'Storage 3' } },
{ data: { id: 'link440', weight: 1, source: 'Solar 1', target: 'Storage 4' } },
{ data: { id: 'link441', weight: 1, source: 'Solar 6', target: 'Storage 4' } },
{ data: { id: 'link442', weight: 1, source: 'MainGrid', target: 'Storage 4' } },
{ data: { id: 'link443', weight: 1, source: 'Wind 1', target: 'Storage 4' } },
{ data: { id: 'link444', weight: 1, source: 'Wind 3', target: 'Storage 4' } },
{ data: { id: 'link445', weight: 1, source: 'Wind 6', target: 'Storage 4' } },
{ data: { id: 'link446', weight: 1, source: 'Wind 4', target: 'Storage 4' } },
{ data: { id: 'link447', weight: 1, source: 'Wind 5', target: 'Storage 4' } },
{ data: { id: 'link450', weight: 1, source: 'Solar 7', target: 'Storage 5' } },
{ data: { id: 'link451', weight: 1, source: 'Solar 2', target: 'Storage 5' } },
{ data: { id: 'link452', weight: 1, source: 'MainGrid', target: 'Storage 5' } },
{ data: { id: 'link453', weight: 1, source: 'Wind 2', target: 'Storage 5' } },
{ data: { id: 'link454', weight: 1, source: 'Wind 8', target: 'Storage 5' } },
{ data: { id: 'link455', weight: 1, source: 'Wind 10', target: 'Storage 5' } },
{ data: { id: 'link456', weight: 1, source: 'Wind 7', target: 'Storage 5' } },
{ data: { id: 'link457', weight: 1, source: 'Wind 9', target: 'Storage 5' } },
{ data: { id: 'link460', weight: 1, source: 'Solar 7', target: 'Storage 6' } },
{ data: { id: 'link461', weight: 1, source: 'Solar 4', target: 'Storage 6' } },
{ data: { id: 'link462', weight: 1, source: 'Solar 1', target: 'Storage 6' } },
{ data: { id: 'link463', weight: 1, source: 'Solar 2', target: 'Storage 6' } },
{ data: { id: 'link464', weight: 1, source: 'Solar 3', target: 'Storage 6' } },
{ data: { id: 'link465', weight: 1, source: 'MainGrid', target: 'Storage 6' } },
{ data: { id: 'link466', weight: 1, source: 'Wind 2', target: 'Storage 6' } },
{ data: { id: 'link467', weight: 1, source: 'Wind 7', target: 'Storage 6' } },
{ data: { id: 'link470', weight: 1, source: 'Solar 7', target: 'Storage 7' } },
{ data: { id: 'link471', weight: 1, source: 'Solar 5', target: 'Storage 7' } },
{ data: { id: 'link472', weight: 1, source: 'Solar 8', target: 'Storage 7' } },
{ data: { id: 'link473', weight: 1, source: 'Solar 2', target: 'Storage 7' } },
{ data: { id: 'link474', weight: 1, source: 'Solar 6', target: 'Storage 7' } },
{ data: { id: 'link475', weight: 1, source: 'MainGrid', target: 'Storage 7' } },
{ data: { id: 'link476', weight: 1, source: 'Wind 2', target: 'Storage 7' } },
{ data: { id: 'link477', weight: 1, source: 'Wind 7', target: 'Storage 7' } },
{ data: { id: 'link480', weight: 1, source: 'Solar 7', target: 'Storage 8' } },
{ data: { id: 'link481', weight: 1, source: 'Solar 10', target: 'Storage 8' } },
{ data: { id: 'link482', weight: 1, source: 'Solar 2', target: 'Storage 8' } },
{ data: { id: 'link483', weight: 1, source: 'Solar 9', target: 'Storage 8' } },
{ data: { id: 'link484', weight: 1, source: 'MainGrid', target: 'Storage 8' } },
{ data: { id: 'link485', weight: 1, source: 'Wind 7', target: 'Storage 8' } },
{ data: { id: 'link486', weight: 1, source: 'Wind 2', target: 'Storage 8' } },
{ data: { id: 'link487', weight: 1, source: 'Wind 1', target: 'Storage 8' } },
{ data: { id: 'link490', weight: 1, source: 'Solar 8', target: 'Storage 9' } },
{ data: { id: 'link491', weight: 1, source: 'Solar 3', target: 'Storage 9' } },
{ data: { id: 'link492', weight: 1, source: 'MainGrid', target: 'Storage 9' } },
{ data: { id: 'link493', weight: 1, source: 'Wind 5', target: 'Storage 9' } },
{ data: { id: 'link494', weight: 1, source: 'Wind 8', target: 'Storage 9' } },
{ data: { id: 'link495', weight: 1, source: 'Wind 4', target: 'Storage 9' } },
{ data: { id: 'link496', weight: 1, source: 'Wind 6', target: 'Storage 9' } },
{ data: { id: 'link497', weight: 1, source: 'Wind 3', target: 'Storage 9' } },
{ data: { id: 'link500', weight: 1, source: 'Solar 8', target: 'Storage 10' } },
{ data: { id: 'link501', weight: 1, source: 'Solar 3', target: 'Storage 10' } },
{ data: { id: 'link502', weight: 1, source: 'MainGrid', target: 'Storage 10' } },
{ data: { id: 'link503', weight: 1, source: 'Wind 3', target: 'Storage 10' } },
{ data: { id: 'link504', weight: 1, source: 'Wind 8', target: 'Storage 10' } },
{ data: { id: 'link505', weight: 1, source: 'Wind 7', target: 'Storage 10' } },
{ data: { id: 'link506', weight: 1, source: 'Wind 9', target: 'Storage 10' } },
{ data: { id: 'link507', weight: 1, source: 'Wind 10', target: 'Storage 10' } },
{ data: { id: 'link510', weight: 1, source: 'Solar 4', target: 'Storage 11' } },
{ data: { id: 'link511', weight: 1, source: 'Solar 8', target: 'Storage 11' } },
{ data: { id: 'link512', weight: 1, source: 'Solar 1', target: 'Storage 11' } },
{ data: { id: 'link513', weight: 1, source: 'Solar 2', target: 'Storage 11' } },
{ data: { id: 'link514', weight: 1, source: 'Solar 3', target: 'Storage 11' } },
{ data: { id: 'link515', weight: 1, source: 'MainGrid', target: 'Storage 11' } },
{ data: { id: 'link516', weight: 1, source: 'Wind 8', target: 'Storage 11' } },
{ data: { id: 'link517', weight: 1, source: 'Wind 3', target: 'Storage 11' } },
{ data: { id: 'link520', weight: 1, source: 'Solar 7', target: 'Storage 12' } },
{ data: { id: 'link521', weight: 1, source: 'Solar 5', target: 'Storage 12' } },
{ data: { id: 'link522', weight: 1, source: 'Solar 8', target: 'Storage 12' } },
{ data: { id: 'link523', weight: 1, source: 'Solar 3', target: 'Storage 12' } },
{ data: { id: 'link524', weight: 1, source: 'Solar 6', target: 'Storage 12' } },
{ data: { id: 'link525', weight: 1, source: 'MainGrid', target: 'Storage 12' } },
{ data: { id: 'link526', weight: 1, source: 'Wind 3', target: 'Storage 12' } },
{ data: { id: 'link527', weight: 1, source: 'Wind 8', target: 'Storage 12' } },
{ data: { id: 'link530', weight: 1, source: 'Solar 4', target: 'Storage 13' } },
{ data: { id: 'link531', weight: 1, source: 'Solar 10', target: 'Storage 13' } },
{ data: { id: 'link532', weight: 1, source: 'Solar 9', target: 'Storage 13' } },
{ data: { id: 'link533', weight: 1, source: 'MainGrid', target: 'Storage 13' } },
{ data: { id: 'link534', weight: 1, source: 'Wind 2', target: 'Storage 13' } },
{ data: { id: 'link535', weight: 1, source: 'Wind 9', target: 'Storage 13' } },
{ data: { id: 'link536', weight: 1, source: 'Wind 4', target: 'Storage 13' } },
{ data: { id: 'link537', weight: 1, source: 'Wind 1', target: 'Storage 13' } },
{ data: { id: 'link540', weight: 1, source: 'Solar 4', target: 'Storage 14' } },
{ data: { id: 'link541', weight: 1, source: 'Solar 9', target: 'Storage 14' } },
{ data: { id: 'link542', weight: 1, source: 'MainGrid', target: 'Storage 14' } },
{ data: { id: 'link543', weight: 1, source: 'Wind 3', target: 'Storage 14' } },
{ data: { id: 'link544', weight: 1, source: 'Wind 4', target: 'Storage 14' } },
{ data: { id: 'link545', weight: 1, source: 'Wind 9', target: 'Storage 14' } },
{ data: { id: 'link546', weight: 1, source: 'Wind 6', target: 'Storage 14' } },
{ data: { id: 'link547', weight: 1, source: 'Wind 5', target: 'Storage 14' } },
{ data: { id: 'link550', weight: 1, source: 'Solar 4', target: 'Storage 15' } },
{ data: { id: 'link551', weight: 1, source: 'Solar 9', target: 'Storage 15' } },
{ data: { id: 'link552', weight: 1, source: 'MainGrid', target: 'Storage 15' } },
{ data: { id: 'link553', weight: 1, source: 'Wind 10', target: 'Storage 15' } },
{ data: { id: 'link554', weight: 1, source: 'Wind 4', target: 'Storage 15' } },
{ data: { id: 'link555', weight: 1, source: 'Wind 8', target: 'Storage 15' } },
{ data: { id: 'link556', weight: 1, source: 'Wind 7', target: 'Storage 15' } },
{ data: { id: 'link557', weight: 1, source: 'Wind 9', target: 'Storage 15' } },
{ data: { id: 'link560', weight: 1, source: 'Solar 4', target: 'Storage 16' } },
{ data: { id: 'link561', weight: 1, source: 'Solar 1', target: 'Storage 16' } },
{ data: { id: 'link562', weight: 1, source: 'Solar 2', target: 'Storage 16' } },
{ data: { id: 'link563', weight: 1, source: 'Solar 3', target: 'Storage 16' } },
{ data: { id: 'link564', weight: 1, source: 'Solar 9', target: 'Storage 16' } },
{ data: { id: 'link565', weight: 1, source: 'MainGrid', target: 'Storage 16' } },
{ data: { id: 'link566', weight: 1, source: 'Wind 9', target: 'Storage 16' } },
{ data: { id: 'link567', weight: 1, source: 'Wind 4', target: 'Storage 16' } },
{ data: { id: 'link570', weight: 1, source: 'Solar 7', target: 'Storage 17' } },
{ data: { id: 'link571', weight: 1, source: 'Solar 5', target: 'Storage 17' } },
{ data: { id: 'link572', weight: 1, source: 'Solar 10', target: 'Storage 17' } },
{ data: { id: 'link573', weight: 1, source: 'Solar 8', target: 'Storage 17' } },
{ data: { id: 'link574', weight: 1, source: 'Solar 6', target: 'Storage 17' } },
{ data: { id: 'link575', weight: 1, source: 'MainGrid', target: 'Storage 17' } },
{ data: { id: 'link576', weight: 1, source: 'Wind 10', target: 'Storage 17' } },
{ data: { id: 'link577', weight: 1, source: 'Wind 5', target: 'Storage 17' } },
{ data: { id: 'link580', weight: 1, source: 'Solar 5', target: 'Storage 18' } },
{ data: { id: 'link581', weight: 1, source: 'Solar 10', target: 'Storage 18' } },
{ data: { id: 'link582', weight: 1, source: 'Solar 9', target: 'Storage 18' } },
{ data: { id: 'link583', weight: 1, source: 'MainGrid', target: 'Storage 18' } },
{ data: { id: 'link584', weight: 1, source: 'Wind 5', target: 'Storage 18' } },
{ data: { id: 'link585', weight: 1, source: 'Wind 1', target: 'Storage 18' } },
{ data: { id: 'link586', weight: 1, source: 'Wind 2', target: 'Storage 18' } },
{ data: { id: 'link587', weight: 1, source: 'Wind 10', target: 'Storage 18' } },
{ data: { id: 'link590', weight: 1, source: 'Solar 5', target: 'Storage 19' } },
{ data: { id: 'link591', weight: 1, source: 'Solar 10', target: 'Storage 19' } },
{ data: { id: 'link592', weight: 1, source: 'MainGrid', target: 'Storage 19' } },
{ data: { id: 'link593', weight: 1, source: 'Wind 6', target: 'Storage 19' } },
{ data: { id: 'link594', weight: 1, source: 'Wind 4', target: 'Storage 19' } },
{ data: { id: 'link595', weight: 1, source: 'Wind 3', target: 'Storage 19' } },
{ data: { id: 'link596', weight: 1, source: 'Wind 10', target: 'Storage 19' } },
{ data: { id: 'link597', weight: 1, source: 'Wind 5', target: 'Storage 19' } },
{ data: { id: 'link600', weight: 1, source: 'Solar 5', target: 'Storage 20' } },
{ data: { id: 'link601', weight: 1, source: 'Solar 10', target: 'Storage 20' } },
{ data: { id: 'link602', weight: 1, source: 'MainGrid', target: 'Storage 20' } },
{ data: { id: 'link603', weight: 1, source: 'Wind 8', target: 'Storage 20' } },
{ data: { id: 'link604', weight: 1, source: 'Wind 9', target: 'Storage 20' } },
{ data: { id: 'link605', weight: 1, source: 'Wind 10', target: 'Storage 20' } },
{ data: { id: 'link606', weight: 1, source: 'Wind 7', target: 'Storage 20' } },
{ data: { id: 'link607', weight: 1, source: 'Wind 5', target: 'Storage 20' } },
]},
layout: { /*ring, grid and*/ name: 'grid', padding: 10 } }); cy.on('tap', 'node', function(e){ var node = e.cyTarget; var neighborhood = node.neighborhood().add(node); cy.elements().addClass('faded'); neighborhood.removeClass('faded'); }); cy.on('tap', function(e){ if( e.cyTarget === cy ){ cy.elements().removeClass('faded'); } }); });
$( document ).ready(function() {$('#agentData tbody').append('<tr id="tidMainGrid"><td>MainGrid</td><td>$0.01</td><td>$1</td><td>$344.62</td><td>$126153.26</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 1"><td>Consumer 1</td><td>$0.5</td><td>$0.00</td><td>-$18.69</td><td>-$6578.69</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 2"><td>Consumer 2</td><td>$0.49</td><td>$0.00</td><td>-$17.7</td><td>-$6626.71</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 3"><td>Consumer 3</td><td>$0.51</td><td>$0.00</td><td>-$21.28</td><td>-$6672.31</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 4"><td>Consumer 4</td><td>$0.51</td><td>$0.00</td><td>-$16.69</td><td>-$6703.38</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 5"><td>Consumer 5</td><td>$0.48</td><td>$0.00</td><td>-$15.3</td><td>-$6526.96</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 6"><td>Consumer 6</td><td>$0.51</td><td>$0.00</td><td>-$17.46</td><td>-$6627.41</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 7"><td>Consumer 7</td><td>$0.61</td><td>$0.00</td><td>-$17.78</td><td>-$6631.47</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 8"><td>Consumer 8</td><td>$0.53</td><td>$0.00</td><td>-$20.04</td><td>-$6621.29</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 9"><td>Consumer 9</td><td>$0.54</td><td>$0.00</td><td>-$17.94</td><td>-$6605.47</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 10"><td>Consumer 10</td><td>$0.52</td><td>$0.00</td><td>-$19.9</td><td>-$6629.16</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 11"><td>Consumer 11</td><td>$0.5</td><td>$0.00</td><td>-$17.92</td><td>-$6683.02</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 12"><td>Consumer 12</td><td>$0.49</td><td>$0.00</td><td>-$17.49</td><td>-$6593.7</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 13"><td>Consumer 13</td><td>$0.54</td><td>$0.00</td><td>-$18.02</td><td>-$6776.6</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 14"><td>Consumer 14</td><td>$0.48</td><td>$0.00</td><td>-$20.31</td><td>-$6681.16</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 15"><td>Consumer 15</td><td>$0.55</td><td>$0.00</td><td>-$18.5</td><td>-$6557.26</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 16"><td>Consumer 16</td><td>$0.63</td><td>$0.00</td><td>-$19.52</td><td>-$6642.93</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 17"><td>Consumer 17</td><td>$0.52</td><td>$0.00</td><td>-$15.36</td><td>-$6631.32</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 18"><td>Consumer 18</td><td>$0.61</td><td>$0.00</td><td>-$16.49</td><td>-$6548.72</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 19"><td>Consumer 19</td><td>$0.53</td><td>$0.00</td><td>-$17.05</td><td>-$6559.63</td></tr>');
$('#agentData tbody').append('<tr id="tidConsumer 20"><td>Consumer 20</td><td>$0.63</td><td>$0.00</td><td>-$19.4</td><td>-$6685.37</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 1"><td>Solar 1</td><td>$0.00</td><td>$0.26</td><td>$2.31</td><td>$815.82</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 2"><td>Solar 2</td><td>$0.00</td><td>$0.27</td><td>$1.82</td><td>$799.4</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 3"><td>Solar 3</td><td>$0.00</td><td>$0.27</td><td>$1.22</td><td>$814.81</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 4"><td>Solar 4</td><td>$0.00</td><td>$0.25</td><td>$2.84</td><td>$806.26</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 5"><td>Solar 5</td><td>$0.00</td><td>$0.24</td><td>$2.23</td><td>$819.93</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 6"><td>Solar 6</td><td>$0.00</td><td>$0.28</td><td>$3.39</td><td>$804.57</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 7"><td>Solar 7</td><td>$0.00</td><td>$0.24</td><td>$1.09</td><td>$827.61</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 8"><td>Solar 8</td><td>$0.00</td><td>$0.26</td><td>$2.82</td><td>$799.56</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 9"><td>Solar 9</td><td>$0.00</td><td>$0.31</td><td>$1.71</td><td>$791.69</td></tr>');
$('#agentData tbody').append('<tr id="tidSolar 10"><td>Solar 10</td><td>$0.00</td><td>$0.25</td><td>$1.86</td><td>$839.33</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 1"><td>Wind 1</td><td>$0.00</td><td>$1.6</td><td>$1.38</td><td>$468.13</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 2"><td>Wind 2</td><td>$0.00</td><td>$1.6</td><td>$0.8</td><td>$474.43</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 3"><td>Wind 3</td><td>$0.00</td><td>$1.6</td><td>$0.76</td><td>$501.5</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 4"><td>Wind 4</td><td>$0.00</td><td>$1.6</td><td>$0.76</td><td>$501.84</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 5"><td>Wind 5</td><td>$0.00</td><td>$1.6</td><td>$1.39</td><td>$505.95</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 6"><td>Wind 6</td><td>$0.00</td><td>$1.6</td><td>$0.76</td><td>$484.85</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 7"><td>Wind 7</td><td>$0.00</td><td>$1.6</td><td>$0.76</td><td>$463.95</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 8"><td>Wind 8</td><td>$0.00</td><td>$1.6</td><td>$1.94</td><td>$475.33</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 9"><td>Wind 9</td><td>$0.00</td><td>$1.6</td><td>$1.38</td><td>$476.73</td></tr>');
$('#agentData tbody').append('<tr id="tidWind 10"><td>Wind 10</td><td>$0.00</td><td>$1.6</td><td>$2.6</td><td>$489.52</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 1"><td>Storage 1</td><td>$0.72</td><td>$0.72</td><td>$-0.76</td><td>$-322.46</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 2"><td>Storage 2</td><td>$0.76</td><td>$0.76</td><td>$-0.89</td><td>$-329.95</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 3"><td>Storage 3</td><td>$0.71</td><td>$0.71</td><td>$-0.76</td><td>$-319.36</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 4"><td>Storage 4</td><td>$0.74</td><td>$0.74</td><td>$-0.89</td><td>$-318.76</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 5"><td>Storage 5</td><td>$0.76</td><td>$0.76</td><td>$-0.95</td><td>$-320.13</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 6"><td>Storage 6</td><td>$0.73</td><td>$0.73</td><td>$-0.61</td><td>$-332.82</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 7"><td>Storage 7</td><td>$0.76</td><td>$0.76</td><td>$-1.03</td><td>$-331.41</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 8"><td>Storage 8</td><td>$0.74</td><td>$0.74</td><td>$-0.75</td><td>$-326.66</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 9"><td>Storage 9</td><td>$0.8</td><td>$0.8</td><td>$-0.87</td><td>$-327.52</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 10"><td>Storage 10</td><td>$0.77</td><td>$0.77</td><td>$-0.83</td><td>$-329.77</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 11"><td>Storage 11</td><td>$0.74</td><td>$0.74</td><td>$-0.82</td><td>$-327.09</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 12"><td>Storage 12</td><td>$0.72</td><td>$0.72</td><td>$-0.83</td><td>$-324.7</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 13"><td>Storage 13</td><td>$0.74</td><td>$0.74</td><td>$-0.94</td><td>$-331.76</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 14"><td>Storage 14</td><td>$0.76</td><td>$0.76</td><td>$-0.66</td><td>$-329.47</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 15"><td>Storage 15</td><td>$0.72</td><td>$0.72</td><td>$-0.57</td><td>$-327.86</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 16"><td>Storage 16</td><td>$0.74</td><td>$0.74</td><td>$-0.55</td><td>$-331.54</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 17"><td>Storage 17</td><td>$0.71</td><td>$0.71</td><td>$-0.8</td><td>$-319.15</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 18"><td>Storage 18</td><td>$0.72</td><td>$0.72</td><td>$-0.55</td><td>$-321.14</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 19"><td>Storage 19</td><td>$0.76</td><td>$0.76</td><td>$-0.82</td><td>$-328.02</td></tr>');
$('#agentData tbody').append('<tr id="tidStorage 20"><td>Storage 20</td><td>$0.76</td><td>$0.76</td><td>$-0.7</td><td>$-332.33</td></tr>');
$('#cCount').text('20');$('#gCount').text('20');$('#sCount').text('20');$('#dCount').text('365');});
